# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Mapbook Report
# TODO: top level description

# %% [markdown]
# ## Imports

import os
from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_ext_ste.tasks import create_directory
from ecoscope_workflows_ext_ste.tasks import download_land_dx
from ecoscope_workflows_ext_ste.tasks import load_landdx_aoi
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column
from ecoscope_workflows_ext_ste.tasks import annotate_gdf_dict_with_geometry_type
from ecoscope_workflows_ext_ste.tasks import create_map_layers_from_annotated_dict
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_core.tasks.io import set_gee_connection
from ecoscope_workflows_ext_ecoscope.tasks.io import get_subjectgroup_observations
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.transformation import classify_is_night
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_classification
from ecoscope_workflows_ext_ste.tasks import label_quarter_status
from ecoscope_workflows_ext_ste.tasks import assign_quarter_status_colors
from ecoscope_workflows_core.tasks.transformation import map_columns
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_core.tasks.transformation import sort_values
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_core.tasks.transformation import map_values_with_unit
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polyline_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_ste.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_ste.tasks import combine_map_layers
from ecoscope_workflows_ext_ste.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_core.tasks.results import merge_widget_views
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import determine_season_windows
from ecoscope_workflows_ext_ste.tasks import create_seasonal_labels
from ecoscope_workflows_ext_ste.tasks import generate_mcp_gdf
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polygon_layer
from ecoscope_workflows_ext_ste.tasks import generate_ecograph_raster
from ecoscope_workflows_ext_ste.tasks import retrieve_feature_gdf
from ecoscope_workflows_ext_ste.tasks import calculate_seasonal_home_range
from ecoscope_workflows_ext_ecoscope.tasks.skip import all_geometry_are_none
from ecoscope_workflows_core.tasks.analysis import dataframe_column_sum
from ecoscope_workflows_ext_ste.tasks import round_off_values
from ecoscope_workflows_core.tasks.results import create_single_value_widget_single_view
from ecoscope_workflows_ext_ste.tasks import dataframe_column_first_unique_str
from ecoscope_workflows_core.tasks.results import create_text_widget_single_view
from ecoscope_workflows_ext_ste.tasks import get_duration
from ecoscope_workflows_ext_ste.tasks import download_file_and_persist
from ecoscope_workflows_core.tasks.analysis import dataframe_column_nunique
from ecoscope_workflows_ext_ste.tasks import build_mapbook_report_template
from ecoscope_workflows_ext_ste.tasks import create_context_page
from ecoscope_workflows_ext_custom.tasks import html_to_png
from ecoscope_workflows_ext_ste.tasks import flatten_tuple
from ecoscope_workflows_ext_ste.tasks import create_mapbook_context
from ecoscope_workflows_ext_ste.tasks import combine_docx_files
from ecoscope_workflows_core.tasks.results import gather_dashboard

# %% [markdown]
# ## Initialize Workflow Metadata

# %%
# parameters

initialize_workflow_metadata_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


initialize_workflow_metadata = (
    set_workflow_details.handle_errors(task_instance_id="initialize_workflow_metadata")
    .partial(**initialize_workflow_metadata_params)
    .call()
)


# %% [markdown]
# ## Define Time Range

# %%
# parameters

define_time_range_params = dict(
    since=...,
    until=...,
)

# %%
# call the task


define_time_range = (
    set_time_range.handle_errors(task_instance_id="define_time_range")
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **define_time_range_params)
    .call()
)


# %% [markdown]
# ## Configure Grouping Strategy

# %%
# parameters

configure_grouping_strategy_params = dict(
    groupers=...,
)

# %%
# call the task


configure_grouping_strategy = (
    set_groupers.handle_errors(task_instance_id="configure_grouping_strategy")
    .partial(**configure_grouping_strategy_params)
    .call()
)


# %% [markdown]
# ## Configure Base Map Layers

# %%
# parameters

configure_base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


configure_base_maps = (
    set_base_maps.handle_errors(task_instance_id="configure_base_maps")
    .partial(**configure_base_maps_params)
    .call()
)


# %% [markdown]
# ## Create Output Directory

# %%
# parameters

create_output_directory_params = dict(
    path_name=...,
)

# %%
# call the task


create_output_directory = (
    create_directory.handle_errors(task_instance_id="create_output_directory")
    .partial(**create_output_directory_params)
    .call()
)


# %% [markdown]
# ## Download LandDx Database and extract

# %%
# parameters

download_ldx_db_params = dict()

# %%
# call the task


download_ldx_db = (
    download_land_dx.handle_errors(task_instance_id="download_ldx_db")
    .partial(
        path=create_output_directory,
        url="https://maraelephant.maps.arcgis.com/sharing/rest/content/items/6da0c9bdd43d4dd0ac59a4f3cd73dcab/data",
        overwrite_existing=False,
        unzip=True,
        **download_ldx_db_params,
    )
    .call()
)


# %% [markdown]
# ## Load AOI from landDx

# %%
# parameters

load_aoi_params = dict(
    aoi=...,
)

# %%
# call the task


load_aoi = (
    load_landdx_aoi.handle_errors(task_instance_id="load_aoi")
    .partial(map_path=download_ldx_db, **load_aoi_params)
    .call()
)


# %% [markdown]
# ## Split LandDx Layers by Type

# %%
# parameters

split_landdx_by_type_params = dict()

# %%
# call the task


split_landdx_by_type = (
    split_gdf_by_column.handle_errors(task_instance_id="split_landdx_by_type")
    .partial(gdf=load_aoi, column="type", **split_landdx_by_type_params)
    .call()
)


# %% [markdown]
# ## Annotate Geometry Types

# %%
# parameters

annotate_geometry_types_params = dict()

# %%
# call the task


annotate_geometry_types = (
    annotate_gdf_dict_with_geometry_type.handle_errors(
        task_instance_id="annotate_geometry_types"
    )
    .partial(gdf_dict=split_landdx_by_type, **annotate_geometry_types_params)
    .call()
)


# %% [markdown]
# ## Style LandDx Map Layers

# %%
# parameters

create_styled_landdx_layers_params = dict(
    style_config=...,
)

# %%
# call the task


create_styled_landdx_layers = (
    create_map_layers_from_annotated_dict.handle_errors(
        task_instance_id="create_styled_landdx_layers"
    )
    .partial(
        annotated_dict=annotate_geometry_types, **create_styled_landdx_layers_params
    )
    .call()
)


# %% [markdown]
# ## Connect to EarthRanger Instance

# %%
# parameters

er_client_name_params = dict(
    data_source=...,
)

# %%
# call the task


er_client_name = (
    set_er_connection.handle_errors(task_instance_id="er_client_name")
    .partial(**er_client_name_params)
    .call()
)


# %% [markdown]
# ## Connect to EE

# %%
# parameters

gee_project_name_params = dict(
    data_source=...,
)

# %%
# call the task


gee_project_name = (
    set_gee_connection.handle_errors(task_instance_id="gee_project_name")
    .partial(**gee_project_name_params)
    .call()
)


# %% [markdown]
# ## Get subject Group Observations from ER

# %%
# parameters

subject_observations_params = dict(
    subject_group_name=...,
)

# %%
# call the task


subject_observations = (
    get_subjectgroup_observations.handle_errors(task_instance_id="subject_observations")
    .partial(
        client=er_client_name,
        time_range=define_time_range,
        raise_on_empty=False,
        include_details=False,
        include_subjectsource_details=False,
        **subject_observations_params,
    )
    .call()
)


# %% [markdown]
# ## Transform Observations to Relocations

# %%
# parameters

subject_reloc_params = dict()

# %%
# call the task


subject_reloc = (
    process_relocations.handle_errors(task_instance_id="subject_reloc")
    .partial(
        observations=subject_observations,
        relocs_columns=[
            "groupby_col",
            "fixtime",
            "junk_status",
            "geometry",
            "extra__subject__name",
            "extra__subject__hex",
            "extra__subject__sex",
            "extra__created_at",
            "extra__subject__subject_subtype",
        ],
        filter_point_coords=[
            {"x": 180.0, "y": 90.0},
            {"x": 0.0, "y": 0.0},
            {"x": 1.0, "y": 1.0},
        ],
        **subject_reloc_params,
    )
    .call()
)


# %% [markdown]
# ## Annotate Relocations with Day/Night Labels

# %%
# parameters

annotate_day_night_params = dict()

# %%
# call the task


annotate_day_night = (
    classify_is_night.handle_errors(task_instance_id="annotate_day_night")
    .partial(relocations=subject_reloc, **annotate_day_night_params)
    .call()
)


# %% [markdown]
# ## Convert Relocations to Trajectories

# %%
# parameters

convert_to_trajectories_params = dict(
    trajectory_segment_filter=...,
)

# %%
# call the task


convert_to_trajectories = (
    relocations_to_trajectory.handle_errors(task_instance_id="convert_to_trajectories")
    .partial(relocations=annotate_day_night, **convert_to_trajectories_params)
    .call()
)


# %% [markdown]
# ## Add Temporal Index to Trajectories

# %%
# parameters

add_temporal_index_to_traj_params = dict()

# %%
# call the task


add_temporal_index_to_traj = (
    add_temporal_index.handle_errors(task_instance_id="add_temporal_index_to_traj")
    .partial(
        df=convert_to_trajectories,
        time_col="segment_start",
        groupers=configure_grouping_strategy,
        cast_to_datetime=True,
        format="mixed",
        **add_temporal_index_to_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Classify Trajectories by Speed

# %%
# parameters

classify_trajectory_speed_bins_params = dict()

# %%
# call the task


classify_trajectory_speed_bins = (
    apply_classification.handle_errors(
        task_instance_id="classify_trajectory_speed_bins"
    )
    .partial(
        df=add_temporal_index_to_traj,
        input_column_name="speed_kmhr",
        output_column_name="speed_bins",
        classification_options={"scheme": "equal_interval", "k": 6},
        label_options={"label_ranges": False, "label_decimals": 1},
        **classify_trajectory_speed_bins_params,
    )
    .call()
)


# %% [markdown]
# ## Label Trajectories by Quarter

# %%
# parameters

label_trajectory_quarters_params = dict()

# %%
# call the task


label_trajectory_quarters = (
    label_quarter_status.handle_errors(task_instance_id="label_trajectory_quarters")
    .partial(
        gdf=classify_trajectory_speed_bins,
        timestamp_col="segment_start",
        **label_trajectory_quarters_params,
    )
    .call()
)


# %% [markdown]
# ## Assign Quarter Status Colors

# %%
# parameters

assign_quarter_colors_traj_params = dict()

# %%
# call the task


assign_quarter_colors_traj = (
    assign_quarter_status_colors.handle_errors(
        task_instance_id="assign_quarter_colors_traj"
    )
    .partial(
        gdf=label_trajectory_quarters,
        hex_column="extra__hex",
        previous_color_hex="#808080",
        **assign_quarter_colors_traj_params,
    )
    .call()
)


# %% [markdown]
# ## Rename reloc columns

# %%
# parameters

rename_reloc_cols_params = dict()

# %%
# call the task


rename_reloc_cols = (
    map_columns.handle_errors(task_instance_id="rename_reloc_cols")
    .partial(
        drop_columns=[],
        retain_columns=[],
        rename_columns={
            "extra__hex": "hex_color",
            "extra__is_night": "is_night",
            "extra__name": "subject_name",
            "extra__sex": "subject_sex",
            "extra__subject_subtype": "subject_subtype",
            "extra__created_at": "created_at",
        },
        df=assign_quarter_colors_traj,
        **rename_reloc_cols_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Trajectories as GPKG

# %%
# parameters

persist_trajectory_df_params = dict(
    filename=...,
)

# %%
# call the task


persist_trajectory_df = (
    persist_df.handle_errors(task_instance_id="persist_trajectory_df")
    .partial(
        df=rename_reloc_cols,
        filetype="gpkg",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_trajectory_df_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Relocations as GPKG

# %%
# parameters

persist_relocs_df_params = dict(
    filename=...,
)

# %%
# call the task


persist_relocs_df = (
    persist_df.handle_errors(task_instance_id="persist_relocs_df")
    .partial(
        df=annotate_day_night,
        filetype="gpkg",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_relocs_df_params,
    )
    .call()
)


# %% [markdown]
# ## Split Trajectories by Group

# %%
# parameters

split_trajectories_by_group_params = dict()

# %%
# call the task


split_trajectories_by_group = (
    split_groups.handle_errors(task_instance_id="split_trajectories_by_group")
    .partial(
        df=rename_reloc_cols,
        groupers=configure_grouping_strategy,
        **split_trajectories_by_group_params,
    )
    .call()
)


# %% [markdown]
# ## Sort Trajectories by Speed Bins

# %%
# parameters

sort_trajectories_by_speed_params = dict(
    ascending=...,
)

# %%
# call the task


sort_trajectories_by_speed = (
    sort_values.handle_errors(task_instance_id="sort_trajectories_by_speed")
    .partial(
        column_name="speed_bins",
        na_position="last",
        **sort_trajectories_by_speed_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Apply Colormap to Speed Bins

# %%
# parameters

apply_speed_colormap_params = dict()

# %%
# call the task


apply_speed_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_speed_colormap")
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_colormap",
        colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
        **apply_speed_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=sort_trajectories_by_speed)
)


# %% [markdown]
# ## Format Speed Bins for Legend

# %%
# parameters

format_speed_bin_labels_params = dict()

# %%
# call the task


format_speed_bin_labels = (
    map_values_with_unit.handle_errors(task_instance_id="format_speed_bin_labels")
    .partial(
        input_column_name="speed_bins",
        output_column_name="speed_bins_formatted",
        original_unit="km/h",
        new_unit="km/h",
        decimal_places=1,
        **format_speed_bin_labels_params,
    )
    .mapvalues(argnames=["df"], argvalues=apply_speed_colormap)
)


# %% [markdown]
# ## Format Speed Values for Display

# %%
# parameters

format_speed_values_params = dict()

# %%
# call the task


format_speed_values = (
    map_values_with_unit.handle_errors(task_instance_id="format_speed_values")
    .partial(
        input_column_name="speed_kmhr",
        output_column_name="speed_kmhr",
        original_unit="km/h",
        new_unit="km/h",
        decimal_places=1,
        **format_speed_values_params,
    )
    .mapvalues(argnames=["df"], argvalues=format_speed_bin_labels)
)


# %% [markdown]
# ## Generate Speedmap Layers

# %%
# parameters

generate_speedmap_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_speedmap_layers = (
    create_polyline_layer.handle_errors(task_instance_id="generate_speedmap_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"color_column": "speed_bins_colormap"},
        legend={
            "label_column": "speed_bins_formatted",
            "color_column": "speed_bins_colormap",
        },
        tooltip_columns=[
            "is_night",
            "subject_name",
            "segment_start",
            "dist_meters",
            "timespan_seconds",
            "subject_sex",
        ],
        **generate_speedmap_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=format_speed_values)
)


# %% [markdown]
# ## Zoom speed trajs by view state

# %%
# parameters

zoom_speed_traj_view_params = dict()

# %%
# call the task


zoom_speed_traj_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_speed_traj_view")
    .partial(pitch=0, bearing=0, **zoom_speed_traj_view_params)
    .mapvalues(argnames=["gdf"], argvalues=format_speed_values)
)


# %% [markdown]
# ## Combine LandDx and Speed Ecomap Layers

# %%
# parameters

ldx_speed_layers_params = dict()

# %%
# call the task


ldx_speed_layers = (
    combine_map_layers.handle_errors(task_instance_id="ldx_speed_layers")
    .partial(static_layers=create_styled_landdx_layers, **ldx_speed_layers_params)
    .mapvalues(argnames=["grouped_layers"], argvalues=generate_speedmap_layers)
)


# %% [markdown]
# ## Zip speedmap layers and zoom values

# %%
# parameters

zip_speed_zoom_values_params = dict()

# %%
# call the task


zip_speed_zoom_values = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_speed_zoom_values")
    .partial(
        left=ldx_speed_layers,
        right=zoom_speed_traj_view,
        **zip_speed_zoom_values_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Speed Ecomaps by Group

# %%
# parameters

draw_speed_ecomap_params = dict()

# %%
# call the task


draw_speed_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_speed_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Speed Values(Km/h)"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_speed_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=zip_speed_zoom_values)
)


# %% [markdown]
# ## Persist Speed Ecomap HTML Paths

# %%
# parameters

persist_speed_ecomap_urls_params = dict(
    filename=...,
)

# %%
# call the task


persist_speed_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_speed_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_speed_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_speed_ecomap)
)


# %% [markdown]
# ## Create Speedmap Widgets

# %%
# parameters

create_speedmap_widgets_params = dict()

# %%
# call the task


create_speedmap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_speedmap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Speedmap", **create_speedmap_widgets_params)
    .map(argnames=["view", "data"], argvalues=persist_speed_ecomap_urls)
)


# %% [markdown]
# ## Merge Speed Ecomap Widgets

# %%
# parameters

merge_speedmap_widgets_params = dict()

# %%
# call the task


merge_speedmap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="merge_speedmap_widgets")
    .partial(widgets=create_speedmap_widgets, **merge_speedmap_widgets_params)
    .call()
)


# %% [markdown]
# ## Sort Trajectories by Night/Day

# %%
# parameters

sort_trajs_by_day_night_params = dict()

# %%
# call the task


sort_trajs_by_day_night = (
    sort_values.handle_errors(task_instance_id="sort_trajs_by_day_night")
    .partial(
        column_name="is_night",
        ascending=False,
        na_position="last",
        **sort_trajs_by_day_night_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Apply Color to Trajectories by Day/Night

# %%
# parameters

apply_day_night_colormap_params = dict()

# %%
# call the task


apply_day_night_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_day_night_colormap")
    .partial(
        colormap=["#292965", "#e7a553"],
        input_column_name="is_night",
        output_column_name="day_night_colors",
        **apply_day_night_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=sort_trajs_by_day_night)
)


# %% [markdown]
# ## Create Day/Night Ecomap Layers

# %%
# parameters

generate_day_night_ecomap_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_day_night_ecomap_layers = (
    create_polyline_layer.handle_errors(
        task_instance_id="generate_day_night_ecomap_layers"
    )
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"color_column": "day_night_colors"},
        legend={"labels": ["Night", "Day"], "colors": ["#292965", "#e7a553"]},
        tooltip_columns=["is_night", "subject_name", "subject_sex"],
        **generate_day_night_ecomap_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=apply_day_night_colormap)
)


# %% [markdown]
# ## Zoom day/night trajs by view state

# %%
# parameters

zoom_dn_view_params = dict()

# %%
# call the task


zoom_dn_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_dn_view")
    .partial(pitch=0, bearing=0, **zoom_dn_view_params)
    .mapvalues(argnames=["gdf"], argvalues=apply_day_night_colormap)
)


# %% [markdown]
# ## Combine LandDx and Day/Night Ecomap Layers

# %%
# parameters

ldx_dn_layers_params = dict()

# %%
# call the task


ldx_dn_layers = (
    combine_map_layers.handle_errors(task_instance_id="ldx_dn_layers")
    .partial(static_layers=create_styled_landdx_layers, **ldx_dn_layers_params)
    .mapvalues(argnames=["grouped_layers"], argvalues=generate_day_night_ecomap_layers)
)


# %% [markdown]
# ## Zip day/night layers and zoom values

# %%
# parameters

dn_view_zip_params = dict()

# %%
# call the task


dn_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="dn_view_zip")
    .partial(left=ldx_dn_layers, right=zoom_dn_view, **dn_view_zip_params)
    .call()
)


# %% [markdown]
# ## Draw Day/Night Ecomaps by Group

# %%
# parameters

draw_day_night_ecomap_params = dict()

# %%
# call the task


draw_day_night_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_day_night_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Night Day Tracks"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_day_night_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=dn_view_zip)
)


# %% [markdown]
# ## Persist Day/Night Ecomap HTML Paths

# %%
# parameters

persist_day_night_ecomap_urls_params = dict(
    filename=...,
)

# %%
# call the task


persist_day_night_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_day_night_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_day_night_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_day_night_ecomap)
)


# %% [markdown]
# ## Create Day/Night Ecomap Widgets

# %%
# parameters

create_day_night_ecomap_widgets_params = dict()

# %%
# call the task


create_day_night_ecomap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_day_night_ecomap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Night Day Tracks", **create_day_night_ecomap_widgets_params)
    .map(argnames=["view", "data"], argvalues=persist_day_night_ecomap_urls)
)


# %% [markdown]
# ## Merge Day/Night Ecomap Widgets

# %%
# parameters

merge_day_night_ecomap_widgets_params = dict()

# %%
# call the task


merge_day_night_ecomap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="merge_day_night_ecomap_widgets")
    .partial(
        widgets=create_day_night_ecomap_widgets, **merge_day_night_ecomap_widgets_params
    )
    .call()
)


# %% [markdown]
# ## Sort Trajectories by Quarter Status

# %%
# parameters

sort_trajs_by_quarter_status_params = dict()

# %%
# call the task


sort_trajs_by_quarter_status = (
    sort_values.handle_errors(task_instance_id="sort_trajs_by_quarter_status")
    .partial(
        column_name="quarter_status",
        ascending=False,
        na_position="last",
        **sort_trajs_by_quarter_status_params,
    )
    .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Create Quarter Status Ecomap Layers

# %%
# parameters

generate_quarter_ecomap_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_quarter_ecomap_layers = (
    create_polyline_layer.handle_errors(
        task_instance_id="generate_quarter_ecomap_layers"
    )
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"color_column": "quarter_status_colors"},
        legend={
            "label_column": "quarter_status",
            "color_column": "quarter_status_colors",
        },
        tooltip_columns=["is_night", "subject_name", "subject_sex", "quarter_status"],
        **generate_quarter_ecomap_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=sort_trajs_by_quarter_status)
)


# %% [markdown]
# ## Zoom quarter movement trajectories by view state

# %%
# parameters

zoom_qm_view_params = dict()

# %%
# call the task


zoom_qm_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_qm_view")
    .partial(pitch=0, bearing=0, **zoom_qm_view_params)
    .mapvalues(argnames=["gdf"], argvalues=format_speed_values)
)


# %% [markdown]
# ## Combine LandDx and Quarter Status Ecomap Layers

# %%
# parameters

combine_quarter_ecomap_layers_params = dict()

# %%
# call the task


combine_quarter_ecomap_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_quarter_ecomap_layers")
    .partial(
        static_layers=create_styled_landdx_layers,
        **combine_quarter_ecomap_layers_params,
    )
    .mapvalues(argnames=["grouped_layers"], argvalues=generate_quarter_ecomap_layers)
)


# %% [markdown]
# ## Zip quarter movement layers and zoom values

# %%
# parameters

qm_view_zip_params = dict()

# %%
# call the task


qm_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="qm_view_zip")
    .partial(
        left=combine_quarter_ecomap_layers, right=zoom_qm_view, **qm_view_zip_params
    )
    .call()
)


# %% [markdown]
# ## Draw Quarter Status Ecomaps by Group

# %%
# parameters

draw_quarter_status_ecomap_params = dict()

# %%
# call the task


draw_quarter_status_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_quarter_status_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Legend"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_quarter_status_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=qm_view_zip)
)


# %% [markdown]
# ## Persist Quarter Status Ecomap HTML Paths

# %%
# parameters

persist_quarter_ecomap_urls_params = dict(
    filename=...,
)

# %%
# call the task


persist_quarter_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_quarter_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_quarter_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_quarter_status_ecomap)
)


# %% [markdown]
# ## Create Quarter Status Ecomap Widgets

# %%
# parameters

create_quarter_ecomap_widgets_params = dict()

# %%
# call the task


create_quarter_ecomap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_quarter_ecomap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Movement Overview", **create_quarter_ecomap_widgets_params)
    .map(argnames=["view", "data"], argvalues=persist_quarter_ecomap_urls)
)


# %% [markdown]
# ## Merge Quarter Status Ecomap Widgets

# %%
# parameters

merge_quarter_ecomap_widgets_params = dict()

# %%
# call the task


merge_quarter_ecomap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="merge_quarter_ecomap_widgets")
    .partial(
        widgets=create_quarter_ecomap_widgets, **merge_quarter_ecomap_widgets_params
    )
    .call()
)


# %% [markdown]
# ## Generate Home Range Ecomap

# %%
# parameters

generate_etd_params = dict(
    auto_scale_or_custom_cell_size=...,
    max_speed_factor=...,
    expansion_factor=...,
)

# %%
# call the task


generate_etd = (
    calculate_elliptical_time_density.handle_errors(task_instance_id="generate_etd")
    .partial(
        crs="ESRI:53042",
        percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.9],
        nodata_value="nan",
        band_count=1,
        **generate_etd_params,
    )
    .mapvalues(argnames=["trajectory_gdf"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Determine Seasonal Windows

# %%
# parameters

determine_seasonal_windows_params = dict()

# %%
# call the task


determine_seasonal_windows = (
    determine_season_windows.handle_errors(
        task_instance_id="determine_seasonal_windows"
    )
    .partial(
        client=gee_project_name,
        time_range=define_time_range,
        **determine_seasonal_windows_params,
    )
    .mapvalues(argnames=["roi"], argvalues=generate_etd)
)


# %% [markdown]
# ## Zip etd and grouped trajectories

# %%
# parameters

zip_etd_and_grouped_trajs_params = dict()

# %%
# call the task


zip_etd_and_grouped_trajs = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_etd_and_grouped_trajs")
    .partial(
        left=determine_seasonal_windows,
        right=split_trajectories_by_group,
        **zip_etd_and_grouped_trajs_params,
    )
    .call()
)


# %% [markdown]
# ## Generate seasonal labels

# %%
# parameters

add_season_labels_params = dict()

# %%
# call the task


add_season_labels = (
    create_seasonal_labels.handle_errors(task_instance_id="add_season_labels")
    .partial(**add_season_labels_params)
    .mapvalues(
        argnames=["total_percentiles", "traj"], argvalues=zip_etd_and_grouped_trajs
    )
)


# %% [markdown]
# ## Generate MCP gdf

# %%
# parameters

calculate_mcp_params = dict()

# %%
# call the task


calculate_mcp = (
    generate_mcp_gdf.handle_errors(task_instance_id="calculate_mcp")
    .partial(planar_crs="ESRI:53042", **calculate_mcp_params)
    .mapvalues(argnames=["gdf"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Apply Colormap to Home Range Percentiles

# %%
# parameters

apply_etd_percentile_colormap_params = dict()

# %%
# call the task


apply_etd_percentile_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_etd_percentile_colormap")
    .partial(
        input_column_name="percentile",
        colormap="RdYlGn",
        output_column_name="percentile_colormap",
        **apply_etd_percentile_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=generate_etd)
)


# %% [markdown]
# ## Create Home Range Ecomap Layers

# %%
# parameters

generate_etd_ecomap_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_etd_ecomap_layers = (
    create_polygon_layer.handle_errors(task_instance_id="generate_etd_ecomap_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "percentile_colormap", "opacity": 0.55},
        legend={"label_column": "percentile", "color_column": "percentile_colormap"},
        tooltip_columns=["percentile"],
        **generate_etd_ecomap_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=apply_etd_percentile_colormap)
)


# %% [markdown]
# ## Create MCP Polygon Layer

# %%
# parameters

generate_mcp_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_mcp_layers = (
    create_polygon_layer.handle_errors(task_instance_id="generate_mcp_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "get_fill_color": "#FFFFFF00",
            "get_line_color": "#dc143c",
            "get_line_width": 2,
            "opacity": 0.55,
            "stroked": True,
        },
        legend={"labels": ["mcp"], "colors": ["#dc143c"]},
        tooltip_columns=["area_km2"],
        **generate_mcp_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=calculate_mcp)
)


# %% [markdown]
# ## Zoom hr movement by view state

# %%
# parameters

zoom_hr_view_params = dict()

# %%
# call the task


zoom_hr_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_hr_view")
    .partial(pitch=0, bearing=0, **zoom_hr_view_params)
    .mapvalues(argnames=["gdf"], argvalues=apply_etd_percentile_colormap)
)


# %% [markdown]
# ## zip mcp and hr

# %%
# parameters

zip_mcp_hr_params = dict()

# %%
# call the task


zip_mcp_hr = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_mcp_hr")
    .partial(
        left=generate_mcp_layers, right=generate_etd_ecomap_layers, **zip_mcp_hr_params
    )
    .call()
)


# %% [markdown]
# ## Combine LandDx and Home Range Ecomap Layers

# %%
# parameters

combine_landdx_hr_ecomap_layers_params = dict()

# %%
# call the task


combine_landdx_hr_ecomap_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_landdx_hr_ecomap_layers")
    .partial(
        static_layers=create_styled_landdx_layers,
        **combine_landdx_hr_ecomap_layers_params,
    )
    .mapvalues(argnames=["grouped_layers"], argvalues=zip_mcp_hr)
)


# %% [markdown]
# ## Zip hr layers and zoom values

# %%
# parameters

hr_view_zip_params = dict()

# %%
# call the task


hr_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="hr_view_zip")
    .partial(
        left=combine_landdx_hr_ecomap_layers, right=zoom_hr_view, **hr_view_zip_params
    )
    .call()
)


# %% [markdown]
# ## Draw Home Range Ecomap

# %%
# parameters

draw_hr_ecomap_params = dict()

# %%
# call the task


draw_hr_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_hr_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "ETD Metrics"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_hr_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=hr_view_zip)
)


# %% [markdown]
# ## Persist Home Range Ecomap HTML Paths

# %%
# parameters

persist_hr_ecomap_urls_params = dict(
    filename=...,
)

# %%
# call the task


persist_hr_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="persist_hr_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_hr_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_hr_ecomap)
)


# %% [markdown]
# ## Create Home Range Ecomap Widgets

# %%
# parameters

create_hr_ecomap_widgets_params = dict()

# %%
# call the task


create_hr_ecomap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_hr_ecomap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Home Range", **create_hr_ecomap_widgets_params)
    .map(argnames=["view", "data"], argvalues=persist_hr_ecomap_urls)
)


# %% [markdown]
# ## Merge Home Range Ecomap Widgets

# %%
# parameters

merge_hr_ecomap_widgets_params = dict()

# %%
# call the task


merge_hr_ecomap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="merge_hr_ecomap_widgets")
    .partial(widgets=create_hr_ecomap_widgets, **merge_hr_ecomap_widgets_params)
    .call()
)


# %% [markdown]
# ## Generate Speed Rasters

# %%
# parameters

generate_speed_raster_params = dict(
    filename=...,
    resolution=...,
    radius=...,
    cutoff=...,
    tortuosity_length=...,
    step_length=...,
    network_metric=...,
)

# %%
# call the task


generate_speed_raster = (
    generate_ecograph_raster.handle_errors(task_instance_id="generate_speed_raster")
    .partial(
        dist_col="dist_meters",
        interpolation="mean",
        movement_covariate="speed",
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **generate_speed_raster_params,
    )
    .mapvalues(argnames=["gdf"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Extract Features from Speed Raster TIFFs

# %%
# parameters

extract_speed_rasters_params = dict()

# %%
# call the task


extract_speed_rasters = (
    retrieve_feature_gdf.handle_errors(task_instance_id="extract_speed_rasters")
    .partial(**extract_speed_rasters_params)
    .mapvalues(argnames=["file_path"], argvalues=generate_speed_raster)
)


# %% [markdown]
# ## Sort Speed Features by Value

# %%
# parameters

sort_speed_features_by_value_params = dict(
    ascending=...,
)

# %%
# call the task


sort_speed_features_by_value = (
    sort_values.handle_errors(task_instance_id="sort_speed_features_by_value")
    .partial(
        column_name="value", na_position="last", **sort_speed_features_by_value_params
    )
    .mapvalues(argnames=["df"], argvalues=extract_speed_rasters)
)


# %% [markdown]
# ## Classify Speed Feature GeoDataFrames

# %%
# parameters

classify_speed_features_params = dict()

# %%
# call the task


classify_speed_features = (
    apply_classification.handle_errors(task_instance_id="classify_speed_features")
    .partial(
        input_column_name="value",
        output_column_name="bins",
        classification_options={"scheme": "natural_breaks", "k": 6},
        label_options={"label_ranges": False, "label_decimals": 1},
        **classify_speed_features_params,
    )
    .mapvalues(argnames=["df"], argvalues=sort_speed_features_by_value)
)


# %% [markdown]
# ## Apply Colormap to Speed Raster Bins

# %%
# parameters

apply_speed_raster_colormap_params = dict()

# %%
# call the task


apply_speed_raster_colormap = (
    apply_color_map.handle_errors(task_instance_id="apply_speed_raster_colormap")
    .partial(
        input_column_name="bins",
        output_column_name="speedraster_bins_colors",
        colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
        **apply_speed_raster_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=classify_speed_features)
)


# %% [markdown]
# ## Format Speed Raster Bin Labels

# %%
# parameters

format_speed_raster_labels_params = dict()

# %%
# call the task


format_speed_raster_labels = (
    map_values_with_unit.handle_errors(task_instance_id="format_speed_raster_labels")
    .partial(
        input_column_name="bins",
        output_column_name="bins_formatted",
        original_unit="km/h",
        new_unit="km/h",
        decimal_places=1,
        **format_speed_raster_labels_params,
    )
    .mapvalues(argnames=["df"], argvalues=apply_speed_raster_colormap)
)


# %% [markdown]
# ## Create Speed Raster Map Layers

# %%
# parameters

generate_raster_layers_params = dict(
    zoom=...,
)

# %%
# call the task


generate_raster_layers = (
    create_polygon_layer.handle_errors(task_instance_id="generate_raster_layers")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "speedraster_bins_colors", "opacity": 0.55},
        legend={
            "label_column": "bins_formatted",
            "color_column": "speedraster_bins_colors",
        },
        tooltip_columns=["value", "bins", "speedraster_bins_colors"],
        **generate_raster_layers_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=format_speed_raster_labels)
)


# %% [markdown]
# ## Zoom speed rasters by view state

# %%
# parameters

zoom_speedraster_view_params = dict()

# %%
# call the task


zoom_speedraster_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_speedraster_view")
    .partial(pitch=0, bearing=0, **zoom_speedraster_view_params)
    .mapvalues(argnames=["gdf"], argvalues=format_speed_raster_labels)
)


# %% [markdown]
# ## Combine LandDx and SpeedRaster Map Layers

# %%
# parameters

combine_seasonal_raster_layers_params = dict()

# %%
# call the task


combine_seasonal_raster_layers = (
    combine_map_layers.handle_errors(task_instance_id="combine_seasonal_raster_layers")
    .partial(
        static_layers=create_styled_landdx_layers,
        **combine_seasonal_raster_layers_params,
    )
    .mapvalues(argnames=["grouped_layers"], argvalues=generate_raster_layers)
)


# %% [markdown]
# ## Zip speedraster layers and zoom values

# %%
# parameters

speedraster_view_zip_params = dict()

# %%
# call the task


speedraster_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="speedraster_view_zip")
    .partial(
        left=combine_seasonal_raster_layers,
        right=zoom_speedraster_view,
        **speedraster_view_zip_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Speed Raster Ecomaps by Group

# %%
# parameters

draw_speed_raster_ecomaps_params = dict()

# %%
# call the task


draw_speed_raster_ecomaps = (
    draw_ecomap.handle_errors(task_instance_id="draw_speed_raster_ecomaps")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Mean Raster Value(Km/h)"},
        static=False,
        title=None,
        max_zoom=20,
        **draw_speed_raster_ecomaps_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=speedraster_view_zip)
)


# %% [markdown]
# ## Persist Speed Raster Ecomap HTML Paths

# %%
# parameters

speed_raster_ecomap_urls_params = dict(
    filename=...,
)

# %%
# call the task


speed_raster_ecomap_urls = (
    persist_text.handle_errors(task_instance_id="speed_raster_ecomap_urls")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **speed_raster_ecomap_urls_params,
    )
    .mapvalues(argnames=["text"], argvalues=draw_speed_raster_ecomaps)
)


# %% [markdown]
# ## Create Speed Raster Ecomap Widgets

# %%
# parameters

speed_raster_ecomap_widgets_params = dict()

# %%
# call the task


speed_raster_ecomap_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="speed_raster_ecomap_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Speed Raster Ecomap", **speed_raster_ecomap_widgets_params)
    .map(argnames=["view", "data"], argvalues=speed_raster_ecomap_urls)
)


# %% [markdown]
# ## Merge Speed Raster Ecomap Widgets

# %%
# parameters

speedraster_ecomap_widgets_params = dict()

# %%
# call the task


speedraster_ecomap_widgets = (
    merge_widget_views.handle_errors(task_instance_id="speedraster_ecomap_widgets")
    .partial(widgets=speed_raster_ecomap_widgets, **speedraster_ecomap_widgets_params)
    .call()
)


# %% [markdown]
# ## Calculate seasonal home range

# %%
# parameters

seasonal_home_range_params = dict(
    percentiles=...,
    auto_scale_or_custom_cell_size=...,
)

# %%
# call the task


seasonal_home_range = (
    calculate_seasonal_home_range.handle_errors(task_instance_id="seasonal_home_range")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
            all_geometry_are_none,
        ],
        unpack_depth=1,
    )
    .partial(groupby_cols=["subject_name", "season"], **seasonal_home_range_params)
    .mapvalues(argnames=["gdf"], argvalues=add_season_labels)
)


# %% [markdown]
# ## Time Density colormap

# %%
# parameters

season_colormap_params = dict()

# %%
# call the task


season_colormap = (
    apply_color_map.handle_errors(task_instance_id="season_colormap")
    .partial(
        input_column_name="season",
        output_column_name="season_colormap",
        colormap=["#f57c00", "#4cf3f7"],
        **season_colormap_params,
    )
    .mapvalues(argnames=["df"], argvalues=seasonal_home_range)
)


# %% [markdown]
# ## Create map layers from Seasons

# %%
# parameters

season_etd_map_layer_params = dict(
    zoom=...,
)

# %%
# call the task


season_etd_map_layer = (
    create_polygon_layer.handle_errors(task_instance_id="season_etd_map_layer")
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={"fill_color_column": "season_colormap", "opacity": 0.65},
        legend={"label_column": "season", "color_column": "season_colormap"},
        tooltip_columns=["percentile"],
        **season_etd_map_layer_params,
    )
    .mapvalues(argnames=["geodataframe"], argvalues=season_colormap)
)


# %% [markdown]
# ## Zoom seasons by view state

# %%
# parameters

zoom_season_view_params = dict()

# %%
# call the task


zoom_season_view = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_season_view")
    .partial(pitch=0, bearing=0, **zoom_season_view_params)
    .mapvalues(argnames=["gdf"], argvalues=season_colormap)
)


# %% [markdown]
# ## Combine Map Layers

# %%
# parameters

comb_season_map_layers_params = dict()

# %%
# call the task


comb_season_map_layers = (
    combine_map_layers.handle_errors(task_instance_id="comb_season_map_layers")
    .partial(static_layers=create_styled_landdx_layers, **comb_season_map_layers_params)
    .mapvalues(argnames=["grouped_layers"], argvalues=season_etd_map_layer)
)


# %% [markdown]
# ## Zip seasons layers and zoom values

# %%
# parameters

seasons_view_zip_params = dict()

# %%
# call the task


seasons_view_zip = (
    zip_grouped_by_key.handle_errors(task_instance_id="seasons_view_zip")
    .partial(
        left=comb_season_map_layers, right=zoom_season_view, **seasons_view_zip_params
    )
    .call()
)


# %% [markdown]
# ## Draw Season Ecomap

# %%
# parameters

seasonal_ecomap_params = dict()

# %%
# call the task


seasonal_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="seasonal_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Seasons"},
        static=False,
        title=None,
        max_zoom=20,
        **seasonal_ecomap_params,
    )
    .mapvalues(argnames=["geo_layers", "view_state"], argvalues=seasons_view_zip)
)


# %% [markdown]
# ## Perist HR ecomap as text

# %%
# parameters

season_etd_ecomap_html_url_params = dict(
    filename=...,
)

# %%
# call the task


season_etd_ecomap_html_url = (
    persist_text.handle_errors(task_instance_id="season_etd_ecomap_html_url")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **season_etd_ecomap_html_url_params,
    )
    .mapvalues(argnames=["text"], argvalues=seasonal_ecomap)
)


# %% [markdown]
# ## Create Map Widgets for Trajectories

# %%
# parameters

season_etd_widgets_single_view_params = dict()

# %%
# call the task


season_etd_widgets_single_view = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="season_etd_widgets_single_view"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Seasonal Home Range", **season_etd_widgets_single_view_params)
    .map(argnames=["view", "data"], argvalues=season_etd_ecomap_html_url)
)


# %% [markdown]
# ## Merge Ecomap Widgets

# %%
# parameters

season_grouped_map_widget_params = dict()

# %%
# call the task


season_grouped_map_widget = (
    merge_widget_views.handle_errors(task_instance_id="season_grouped_map_widget")
    .partial(widgets=season_etd_widgets_single_view, **season_grouped_map_widget_params)
    .call()
)


# %% [markdown]
# ## Calculate Total MCP Area

# %%
# parameters

total_mcp_area_params = dict()

# %%
# call the task


total_mcp_area = (
    dataframe_column_sum.handle_errors(task_instance_id="total_mcp_area")
    .partial(column_name="area_km2", **total_mcp_area_params)
    .mapvalues(argnames=["df"], argvalues=calculate_mcp)
)


# %% [markdown]
# ## Round off mcp area to 2 decimal_places

# %%
# parameters

round_mcp_area_params = dict()

# %%
# call the task


round_mcp_area = (
    round_off_values.handle_errors(task_instance_id="round_mcp_area")
    .partial(dp=2, **round_mcp_area_params)
    .mapvalues(argnames=["value"], argvalues=total_mcp_area)
)


# %% [markdown]
# ## Calculate Total Grid Area

# %%
# parameters

total_grid_area_params = dict()

# %%
# call the task


total_grid_area = (
    dataframe_column_sum.handle_errors(task_instance_id="total_grid_area")
    .partial(column_name="area_sqkm", **total_grid_area_params)
    .mapvalues(argnames=["df"], argvalues=generate_etd)
)


# %% [markdown]
# ## Round off grid area to 2 decimal_places

# %%
# parameters

round_grid_area_params = dict()

# %%
# call the task


round_grid_area = (
    round_off_values.handle_errors(task_instance_id="round_grid_area")
    .partial(dp=2, **round_grid_area_params)
    .mapvalues(argnames=["value"], argvalues=total_grid_area)
)


# %% [markdown]
# ## Create Single Value Widgets for Total MCP Area Per Group

# %%
# parameters

total_mcp_sv_widgets_params = dict()

# %%
# call the task


total_mcp_sv_widgets = (
    create_single_value_widget_single_view.handle_errors(
        task_instance_id="total_mcp_sv_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total MCP Area (Km2)", decimal_places=1, **total_mcp_sv_widgets_params
    )
    .map(argnames=["view", "data"], argvalues=round_mcp_area)
)


# %% [markdown]
# ## Merge per group Total MCP Area SV widgets

# %%
# parameters

total_mcp_grouped_sv_widget_params = dict()

# %%
# call the task


total_mcp_grouped_sv_widget = (
    merge_widget_views.handle_errors(task_instance_id="total_mcp_grouped_sv_widget")
    .partial(widgets=total_mcp_sv_widgets, **total_mcp_grouped_sv_widget_params)
    .call()
)


# %% [markdown]
# ## Create Single Value Widgets for Total grid Area Per Group

# %%
# parameters

total_grid_sv_widgets_params = dict()

# %%
# call the task


total_grid_sv_widgets = (
    create_single_value_widget_single_view.handle_errors(
        task_instance_id="total_grid_sv_widgets"
    )
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Total Grid Area(Km2)", decimal_places=1, **total_grid_sv_widgets_params
    )
    .map(argnames=["view", "data"], argvalues=round_grid_area)
)


# %% [markdown]
# ## Merge per group Total Grid Area SV widgets

# %%
# parameters

total_grid_grouped_sv_widget_params = dict()

# %%
# call the task


total_grid_grouped_sv_widget = (
    merge_widget_views.handle_errors(task_instance_id="total_grid_grouped_sv_widget")
    .partial(widgets=total_grid_sv_widgets, **total_grid_grouped_sv_widget_params)
    .call()
)


# %% [markdown]
# ## Determine subject gender

# %%
# parameters

subject_gender_params = dict()

# %%
# call the task


subject_gender = (
    dataframe_column_first_unique_str.handle_errors(task_instance_id="subject_gender")
    .partial(column_name="subject_sex", **subject_gender_params)
    .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Create Single Value Widgets for Subject Gender Per Group

# %%
# parameters

gender_widgets_params = dict()

# %%
# call the task


gender_widgets = (
    create_text_widget_single_view.handle_errors(task_instance_id="gender_widgets")
    .skipif(
        conditions=[
            never,
        ],
        unpack_depth=1,
    )
    .partial(title="Gender", **gender_widgets_params)
    .map(argnames=["view", "data"], argvalues=subject_gender)
)


# %% [markdown]
# ## Merge per group Gender SV widgets

# %%
# parameters

gender_sv_widget_params = dict()

# %%
# call the task


gender_sv_widget = (
    merge_widget_views.handle_errors(task_instance_id="gender_sv_widget")
    .partial(widgets=gender_widgets, **gender_sv_widget_params)
    .call()
)


# %% [markdown]
# ## Get Report Duration

# %%
# parameters

report_duration_params = dict()

# %%
# call the task


report_duration = (
    get_duration.handle_errors(task_instance_id="report_duration")
    .partial(time_range=define_time_range, time_unit="months", **report_duration_params)
    .call()
)


# %% [markdown]
# ## Round off report duration to 2 decimal_places

# %%
# parameters

round_report_duration_params = dict()

# %%
# call the task


round_report_duration = (
    round_off_values.handle_errors(task_instance_id="round_report_duration")
    .partial(dp=2, value=report_duration, **round_report_duration_params)
    .call()
)


# %% [markdown]
# ## Get subject name

# %%
# parameters

get_subject_name_params = dict()

# %%
# call the task


get_subject_name = (
    dataframe_column_first_unique_str.handle_errors(task_instance_id="get_subject_name")
    .partial(column_name="subject_name", **get_subject_name_params)
    .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
)


# %% [markdown]
# ## Download Mapbook cover page templates

# %%
# parameters

download_mapbook_cover_page_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


download_mapbook_cover_page = (
    download_file_and_persist.handle_errors(
        task_instance_id="download_mapbook_cover_page"
    )
    .partial(
        url="https://www.dropbox.com/scl/fi/ky7lbuccf80pf1bsulzbh/cover_page_v2.docx?rlkey=zqdn23e7n9lgm2potqw880c9d&st=ehh51990&dl=0",
        output_path=create_output_directory,
        overwrite_existing=False,
        **download_mapbook_cover_page_params,
    )
    .call()
)


# %% [markdown]
# ## Download Mapbook section templates

# %%
# parameters

download_sect_templates_params = dict(
    retries=...,
    unzip=...,
)

# %%
# call the task


download_sect_templates = (
    download_file_and_persist.handle_errors(task_instance_id="download_sect_templates")
    .partial(
        url="https://www.dropbox.com/scl/fi/ellj1775r4mum7wx44fz3/mapbook_subject_template_v2.docx?rlkey=9618t5pxrnqflyzp9139qc5dy&st=9dvb8mgc&dl=0",
        output_path=create_output_directory,
        overwrite_existing=False,
        **download_sect_templates_params,
    )
    .call()
)


# %% [markdown]
# ## Download Logo Path

# %%
# parameters

download_logo_path_params = dict(
    url=...,
    retries=...,
    unzip=...,
)

# %%
# call the task


download_logo_path = (
    download_file_and_persist.handle_errors(task_instance_id="download_logo_path")
    .partial(
        output_path=create_output_directory,
        overwrite_existing=False,
        **download_logo_path_params,
    )
    .call()
)


# %% [markdown]
# ## Unique subjects on relocs

# %%
# parameters

unique_subjects_params = dict()

# %%
# call the task


unique_subjects = (
    dataframe_column_nunique.handle_errors(task_instance_id="unique_subjects")
    .partial(df=rename_reloc_cols, column_name="subject_name", **unique_subjects_params)
    .call()
)


# %% [markdown]
# ## Create cover template context

# %%
# parameters

create_cover_template_context_params = dict()

# %%
# call the task


create_cover_template_context = (
    build_mapbook_report_template.handle_errors(
        task_instance_id="create_cover_template_context"
    )
    .partial(
        count=unique_subjects,
        org_logo_path=download_logo_path,
        report_period=define_time_range,
        prepared_by="Ecoscope",
        **create_cover_template_context_params,
    )
    .call()
)


# %% [markdown]
# ## Persist context to cover template

# %%
# parameters

persist_context_cover_params = dict(
    filename=...,
)

# %%
# call the task


persist_context_cover = (
    create_context_page.handle_errors(task_instance_id="persist_context_cover")
    .partial(
        logo_width_cm=5.25,
        logo_height_cm=1.93,
        template_path=download_mapbook_cover_page,
        output_directory=create_output_directory,
        context=create_cover_template_context,
        **persist_context_cover_params,
    )
    .call()
)


# %% [markdown]
# ## Convert speedmap html to png

# %%
# parameters

convert_speedmap_html_to_png_params = dict()

# %%
# call the task


convert_speedmap_html_to_png = (
    html_to_png.handle_errors(task_instance_id="convert_speedmap_html_to_png")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convert_speedmap_html_to_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_speed_ecomap_urls)
)


# %% [markdown]
# ## Convert day/night html to png

# %%
# parameters

convert_day_night_html_to_png_params = dict()

# %%
# call the task


convert_day_night_html_to_png = (
    html_to_png.handle_errors(task_instance_id="convert_day_night_html_to_png")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convert_day_night_html_to_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_day_night_ecomap_urls)
)


# %% [markdown]
# ## Convert quarter html to png

# %%
# parameters

convert_quarter_html_to_png_params = dict()

# %%
# call the task


convert_quarter_html_to_png = (
    html_to_png.handle_errors(task_instance_id="convert_quarter_html_to_png")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convert_quarter_html_to_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_quarter_ecomap_urls)
)


# %% [markdown]
# ## Convert home range html to png

# %%
# parameters

convert_hr_html_to_png_params = dict()

# %%
# call the task


convert_hr_html_to_png = (
    html_to_png.handle_errors(task_instance_id="convert_hr_html_to_png")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convert_hr_html_to_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=persist_hr_ecomap_urls)
)


# %% [markdown]
# ## Convert speed raster html to png

# %%
# parameters

convert_speed_raster_html_to_png_params = dict()

# %%
# call the task


convert_speed_raster_html_to_png = (
    html_to_png.handle_errors(task_instance_id="convert_speed_raster_html_to_png")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convert_speed_raster_html_to_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=speed_raster_ecomap_urls)
)


# %% [markdown]
# ## Convert seasonal home range html to png

# %%
# parameters

convert_seasonal_hr_html_to_png_params = dict()

# %%
# call the task


convert_seasonal_hr_html_to_png = (
    html_to_png.handle_errors(task_instance_id="convert_seasonal_hr_html_to_png")
    .partial(
        output_dir=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        config={"wait_for_timeout": 20000},
        **convert_seasonal_hr_html_to_png_params,
    )
    .mapvalues(argnames=["html_path"], argvalues=season_etd_ecomap_html_url)
)


# %% [markdown]
# ## Zip grid and mcp

# %%
# parameters

zip_grid_mcp_params = dict()

# %%
# call the task


zip_grid_mcp = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_grid_mcp")
    .partial(left=round_grid_area, right=round_mcp_area, **zip_grid_mcp_params)
    .call()
)


# %% [markdown]
# ## Zip with quarter png

# %%
# parameters

zip_grid_mcp_quarter_params = dict()

# %%
# call the task


zip_grid_mcp_quarter = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_grid_mcp_quarter")
    .partial(
        left=zip_grid_mcp,
        right=convert_quarter_html_to_png,
        **zip_grid_mcp_quarter_params,
    )
    .call()
)


# %% [markdown]
# ## Zip with hr png

# %%
# parameters

zip_grid_mcp_quarter_hr_params = dict()

# %%
# call the task


zip_grid_mcp_quarter_hr = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_grid_mcp_quarter_hr")
    .partial(
        left=zip_grid_mcp_quarter,
        right=convert_hr_html_to_png,
        **zip_grid_mcp_quarter_hr_params,
    )
    .call()
)


# %% [markdown]
# ## Zip with speed raster png

# %%
# parameters

zip_grid_mcp_speedraster_params = dict()

# %%
# call the task


zip_grid_mcp_speedraster = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_grid_mcp_speedraster")
    .partial(
        left=zip_grid_mcp_quarter_hr,
        right=convert_speed_raster_html_to_png,
        **zip_grid_mcp_speedraster_params,
    )
    .call()
)


# %% [markdown]
# ## Zip with day/night png

# %%
# parameters

zip_grid_mcp_dn_params = dict()

# %%
# call the task


zip_grid_mcp_dn = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_grid_mcp_dn")
    .partial(
        left=zip_grid_mcp_speedraster,
        right=convert_day_night_html_to_png,
        **zip_grid_mcp_dn_params,
    )
    .call()
)


# %% [markdown]
# ## Zip with speedmap png

# %%
# parameters

zip_grid_dn_speedmap_params = dict()

# %%
# call the task


zip_grid_dn_speedmap = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_grid_dn_speedmap")
    .partial(
        left=zip_grid_mcp_dn,
        right=convert_speedmap_html_to_png,
        **zip_grid_dn_speedmap_params,
    )
    .call()
)


# %% [markdown]
# ## Zip with seasonal hr png (final)

# %%
# parameters

zip_all_mapbook_context_inputs_params = dict()

# %%
# call the task


zip_all_mapbook_context_inputs = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_all_mapbook_context_inputs")
    .partial(
        left=zip_grid_dn_speedmap,
        right=convert_seasonal_hr_html_to_png,
        **zip_all_mapbook_context_inputs_params,
    )
    .call()
)


# %% [markdown]
# ## Zip with subject name

# %%
# parameters

zip_all_with_name_params = dict()

# %%
# call the task


zip_all_with_name = (
    zip_grouped_by_key.handle_errors(task_instance_id="zip_all_with_name")
    .partial(
        left=zip_all_mapbook_context_inputs,
        right=get_subject_name,
        **zip_all_with_name_params,
    )
    .call()
)


# %% [markdown]
# ## Flatten zipped mapbook context inputs

# %%
# parameters

flatten_mbook_context_params = dict()

# %%
# call the task


flatten_mbook_context = (
    flatten_tuple.handle_errors(task_instance_id="flatten_mbook_context")
    .partial(**flatten_mbook_context_params)
    .mapvalues(argnames=["nested"], argvalues=zip_all_with_name)
)


# %% [markdown]
# ## Create individual mapbook context

# %%
# parameters

individual_mapbook_context_params = dict(
    filename=...,
    validate_images=...,
    box_h_cm=...,
    box_w_cm=...,
)

# %%
# call the task


individual_mapbook_context = (
    create_mapbook_context.handle_errors(task_instance_id="individual_mapbook_context")
    .partial(
        template_path=download_sect_templates,
        output_directory=create_output_directory,
        subject_name=get_subject_name,
        time_period=define_time_range,
        period=round_report_duration,
        **individual_mapbook_context_params,
    )
    .mapvalues(
        argnames=[
            "grid_area",
            "mcp_area",
            "movement_tracks_ecomap",
            "home_range_ecomap",
            "speed_raster_ecomap",
            "night_day_ecomap",
            "speedmap",
            "seasonal_homerange",
            "subject_name",
        ],
        argvalues=flatten_mbook_context,
    )
)


# %% [markdown]
# ## Generate final mapbook report

# %%
# parameters

generate_mapbook_report_params = dict()

# %%
# call the task


generate_mapbook_report = (
    combine_docx_files.handle_errors(task_instance_id="generate_mapbook_report")
    .partial(
        cover_page_path=persist_context_cover,
        output_directory=create_output_directory,
        filename="mapbook_report.docx",
        context_page_items=individual_mapbook_context,
        **generate_mapbook_report_params,
    )
    .call()
)


# %% [markdown]
# ## Mapbook Dashboard

# %%
# parameters

mapbook_dashboard_params = dict()

# %%
# call the task


mapbook_dashboard = (
    gather_dashboard.handle_errors(task_instance_id="mapbook_dashboard")
    .partial(
        details=initialize_workflow_metadata,
        widgets=[
            gender_sv_widget,
            total_mcp_grouped_sv_widget,
            total_grid_grouped_sv_widget,
            merge_speedmap_widgets,
            merge_day_night_ecomap_widgets,
            merge_quarter_ecomap_widgets,
            merge_hr_ecomap_widgets,
            speedraster_ecomap_widgets,
            season_grouped_map_widget,
        ],
        time_range=define_time_range,
        groupers=configure_grouping_strategy,
        **mapbook_dashboard_params,
    )
    .call()
)
