# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details

# ruff: noqa: E402

"""WARNING: This file is generated in a testing context and should not be used in production.
Lines specific to the testing context are marked with a test tube emoji (🧪) to indicate
that they would not be included (or would be different) in the production version of this file.
"""

import json
import os
import warnings  # 🧪
from ecoscope_workflows_core.testing import create_task_magicmock  # 🧪


from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_ext_ecoscope.tasks.results import set_base_maps
from ecoscope_workflows_ext_ste.tasks import create_directory
from ecoscope_workflows_ext_ste.tasks import download_land_dx
from ecoscope_workflows_ext_ste.tasks import load_landdx_aoi
from ecoscope_workflows_ext_ste.tasks import split_gdf_by_column
from ecoscope_workflows_ext_ste.tasks import annotate_gdf_dict_with_geometry_type
from ecoscope_workflows_ext_ste.tasks import create_map_layers_from_annotated_dict
from ecoscope_workflows_core.tasks.io import set_er_connection
from ecoscope_workflows_core.tasks.io import set_gee_connection

get_subjectgroup_observations = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="get_subjectgroup_observations",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import process_relocations
from ecoscope_workflows_ext_ecoscope.tasks.transformation import classify_is_night
from ecoscope_workflows_ext_ecoscope.tasks.preprocessing import (
    relocations_to_trajectory,
)
from ecoscope_workflows_core.tasks.transformation import add_temporal_index
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_classification
from ecoscope_workflows_ext_ste.tasks import label_quarter_status
from ecoscope_workflows_ext_ecoscope.tasks.analysis import (
    calculate_elliptical_time_density,
)

determine_season_windows = create_task_magicmock(  # 🧪
    anchor="ecoscope_workflows_ext_ecoscope.tasks.io",  # 🧪
    func_name="determine_season_windows",  # 🧪
)  # 🧪
from ecoscope_workflows_ext_ste.tasks import create_seasonal_labels
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df
from ecoscope_workflows_core.tasks.groupby import split_groups
from ecoscope_workflows_core.tasks.transformation import sort_values
from ecoscope_workflows_ext_ecoscope.tasks.transformation import apply_color_map
from ecoscope_workflows_core.tasks.transformation import map_values_with_unit
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polyline_layer
from ecoscope_workflows_core.tasks.skip import any_is_empty_df
from ecoscope_workflows_core.tasks.skip import any_dependency_skipped
from ecoscope_workflows_ext_ste.tasks import create_view_state_from_gdf
from ecoscope_workflows_ext_ste.tasks import combine_map_layers
from ecoscope_workflows_ext_ste.tasks import zip_grouped_by_key
from ecoscope_workflows_ext_ecoscope.tasks.results import draw_ecomap
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import create_map_widget_single_view
from ecoscope_workflows_core.tasks.skip import never
from ecoscope_workflows_core.tasks.results import merge_widget_views
from ecoscope_workflows_ext_ste.tasks import calculate_etd_by_groups
from ecoscope_workflows_ext_ste.tasks import generate_mcp_gdf
from ecoscope_workflows_ext_ecoscope.tasks.results import create_polygon_layer
from ecoscope_workflows_ext_ste.tasks import generate_ecograph_raster
from ecoscope_workflows_ext_ste.tasks import retrieve_feature_gdf
from ecoscope_workflows_core.tasks.analysis import dataframe_column_sum
from ecoscope_workflows_core.tasks.results import create_single_value_widget_single_view
from ecoscope_workflows_ext_ste.tasks import dataframe_column_first_unique_str
from ecoscope_workflows_core.tasks.results import create_text_widget_single_view
from ecoscope_workflows_core.tasks.results import gather_dashboard

from ..params import Params


def main(params: Params):
    warnings.warn("This test script should not be used in production!")  # 🧪

    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    initialize_workflow_metadata = (
        set_workflow_details.validate()
        .handle_errors(task_instance_id="initialize_workflow_metadata")
        .partial(**(params_dict.get("initialize_workflow_metadata") or {}))
        .call()
    )

    define_time_range = (
        set_time_range.validate()
        .handle_errors(task_instance_id="define_time_range")
        .partial(
            time_format="%d %b %Y %H:%M:%S %Z",
            **(params_dict.get("define_time_range") or {}),
        )
        .call()
    )

    configure_grouping_strategy = (
        set_groupers.validate()
        .handle_errors(task_instance_id="configure_grouping_strategy")
        .partial(**(params_dict.get("configure_grouping_strategy") or {}))
        .call()
    )

    configure_base_maps = (
        set_base_maps.validate()
        .handle_errors(task_instance_id="configure_base_maps")
        .partial(**(params_dict.get("configure_base_maps") or {}))
        .call()
    )

    create_output_directory = (
        create_directory.validate()
        .handle_errors(task_instance_id="create_output_directory")
        .partial(**(params_dict.get("create_output_directory") or {}))
        .call()
    )

    retrieve_landdx_database = (
        download_land_dx.validate()
        .handle_errors(task_instance_id="retrieve_landdx_database")
        .partial(
            path=create_output_directory,
            **(params_dict.get("retrieve_landdx_database") or {}),
        )
        .call()
    )

    load_aoi = (
        load_landdx_aoi.validate()
        .handle_errors(task_instance_id="load_aoi")
        .partial(
            map_path=retrieve_landdx_database, **(params_dict.get("load_aoi") or {})
        )
        .call()
    )

    split_landdx_by_type = (
        split_gdf_by_column.validate()
        .handle_errors(task_instance_id="split_landdx_by_type")
        .partial(
            gdf=load_aoi,
            column="type",
            **(params_dict.get("split_landdx_by_type") or {}),
        )
        .call()
    )

    annotate_geometry_types = (
        annotate_gdf_dict_with_geometry_type.validate()
        .handle_errors(task_instance_id="annotate_geometry_types")
        .partial(
            gdf_dict=split_landdx_by_type,
            **(params_dict.get("annotate_geometry_types") or {}),
        )
        .call()
    )

    create_styled_landdx_layers = (
        create_map_layers_from_annotated_dict.validate()
        .handle_errors(task_instance_id="create_styled_landdx_layers")
        .partial(
            annotated_dict=annotate_geometry_types,
            **(params_dict.get("create_styled_landdx_layers") or {}),
        )
        .call()
    )

    er_client_name = (
        set_er_connection.validate()
        .handle_errors(task_instance_id="er_client_name")
        .partial(**(params_dict.get("er_client_name") or {}))
        .call()
    )

    gee_project_name = (
        set_gee_connection.validate()
        .handle_errors(task_instance_id="gee_project_name")
        .partial(**(params_dict.get("gee_project_name") or {}))
        .call()
    )

    subject_observations = (
        get_subjectgroup_observations.validate()
        .handle_errors(task_instance_id="subject_observations")
        .partial(
            client=er_client_name,
            time_range=define_time_range,
            raise_on_empty=False,
            include_details=False,
            include_subjectsource_details=False,
            **(params_dict.get("subject_observations") or {}),
        )
        .call()
    )

    subject_reloc = (
        process_relocations.validate()
        .handle_errors(task_instance_id="subject_reloc")
        .partial(
            observations=subject_observations,
            relocs_columns=[
                "groupby_col",
                "fixtime",
                "junk_status",
                "geometry",
                "extra__subject__name",
                "extra__subject__subject_subtype",
                "extra__subject__sex",
                "extra__created_at",
            ],
            filter_point_coords=[
                {"x": 180.0, "y": 90.0},
                {"x": 0.0, "y": 0.0},
                {"x": 1.0, "y": 1.0},
            ],
            **(params_dict.get("subject_reloc") or {}),
        )
        .call()
    )

    annotate_day_night = (
        classify_is_night.validate()
        .handle_errors(task_instance_id="annotate_day_night")
        .partial(
            relocations=subject_reloc, **(params_dict.get("annotate_day_night") or {})
        )
        .call()
    )

    convert_to_trajectories = (
        relocations_to_trajectory.validate()
        .handle_errors(task_instance_id="convert_to_trajectories")
        .partial(
            relocations=annotate_day_night,
            **(params_dict.get("convert_to_trajectories") or {}),
        )
        .call()
    )

    add_temporal_index_to_traj = (
        add_temporal_index.validate()
        .handle_errors(task_instance_id="add_temporal_index_to_traj")
        .partial(
            df=convert_to_trajectories,
            time_col="segment_start",
            groupers=configure_grouping_strategy,
            cast_to_datetime=True,
            format="mixed",
            **(params_dict.get("add_temporal_index_to_traj") or {}),
        )
        .call()
    )

    classify_trajectory_speed_bins = (
        apply_classification.validate()
        .handle_errors(task_instance_id="classify_trajectory_speed_bins")
        .partial(
            df=add_temporal_index_to_traj,
            input_column_name="speed_kmhr",
            output_column_name="speed_bins",
            classification_options={"scheme": "equal_interval", "k": 6},
            label_options={"label_ranges": False, "label_decimals": 1},
            **(params_dict.get("classify_trajectory_speed_bins") or {}),
        )
        .call()
    )

    label_trajectory_quarters = (
        label_quarter_status.validate()
        .handle_errors(task_instance_id="label_trajectory_quarters")
        .partial(
            gdf=classify_trajectory_speed_bins,
            timestamp_col="segment_start",
            **(params_dict.get("label_trajectory_quarters") or {}),
        )
        .call()
    )

    generate_seasonal_etd = (
        calculate_elliptical_time_density.validate()
        .handle_errors(task_instance_id="generate_seasonal_etd")
        .partial(
            crs="ESRI:53042",
            percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
            nodata_value="nan",
            band_count=1,
            trajectory_gdf=label_trajectory_quarters,
            **(params_dict.get("generate_seasonal_etd") or {}),
        )
        .call()
    )

    determine_seasonal_windows = (
        determine_season_windows.validate()
        .handle_errors(task_instance_id="determine_seasonal_windows")
        .partial(
            client=gee_project_name,
            roi=generate_seasonal_etd,
            time_range=define_time_range,
            **(params_dict.get("determine_seasonal_windows") or {}),
        )
        .call()
    )

    add_season_labels = (
        create_seasonal_labels.validate()
        .handle_errors(task_instance_id="add_season_labels")
        .partial(
            traj=label_trajectory_quarters,
            total_percentiles=determine_seasonal_windows,
            **(params_dict.get("add_season_labels") or {}),
        )
        .call()
    )

    persist_traj_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_traj_df")
        .partial(
            df=add_season_labels,
            filetype="gpkg",
            root_path=create_output_directory,
            **(params_dict.get("persist_traj_df") or {}),
        )
        .call()
    )

    persist_relocs_df = (
        persist_df.validate()
        .handle_errors(task_instance_id="persist_relocs_df")
        .partial(
            df=annotate_day_night,
            filetype="gpkg",
            root_path=create_output_directory,
            **(params_dict.get("persist_relocs_df") or {}),
        )
        .call()
    )

    split_trajectories_by_group = (
        split_groups.validate()
        .handle_errors(task_instance_id="split_trajectories_by_group")
        .partial(
            df=add_season_labels,
            groupers=configure_grouping_strategy,
            **(params_dict.get("split_trajectories_by_group") or {}),
        )
        .call()
    )

    sort_trajectories_by_speed = (
        sort_values.validate()
        .handle_errors(task_instance_id="sort_trajectories_by_speed")
        .partial(
            column_name="speed_bins",
            na_position="last",
            **(params_dict.get("sort_trajectories_by_speed") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    apply_speed_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_speed_colormap")
        .partial(
            input_column_name="speed_bins",
            output_column_name="speed_bins_colormap",
            colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
            **(params_dict.get("apply_speed_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_trajectories_by_speed)
    )

    format_speed_bin_labels = (
        map_values_with_unit.validate()
        .handle_errors(task_instance_id="format_speed_bin_labels")
        .partial(
            input_column_name="speed_bins",
            output_column_name="speed_bins_formatted",
            original_unit="km/h",
            new_unit="km/h",
            decimal_places=1,
            **(params_dict.get("format_speed_bin_labels") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=apply_speed_colormap)
    )

    format_speed_values = (
        map_values_with_unit.validate()
        .handle_errors(task_instance_id="format_speed_values")
        .partial(
            input_column_name="speed_kmhr",
            output_column_name="speed_kmhr",
            original_unit="km/h",
            new_unit="km/h",
            decimal_places=1,
            **(params_dict.get("format_speed_values") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=format_speed_bin_labels)
    )

    generate_speed_ecomap_layers = (
        create_polyline_layer.validate()
        .handle_errors(task_instance_id="generate_speed_ecomap_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "speed_bins_colormap"},
            legend={
                "label_column": "speed_bins_formatted",
                "color_column": "speed_bins_colormap",
            },
            tooltip_columns=[
                "extra__is_night",
                "extra__name",
                "segment_start",
                "dist_meters",
                "timespan_seconds",
                "extra__sex",
            ],
            **(params_dict.get("generate_speed_ecomap_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=format_speed_values)
    )

    zoom_traj_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_traj_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_traj_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=format_speed_values)
    )

    combine_landdx_speed_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="combine_landdx_speed_layers")
        .partial(
            static_layers=create_styled_landdx_layers,
            **(params_dict.get("combine_landdx_speed_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=generate_speed_ecomap_layers)
    )

    speedvalues_view_zip = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="speedvalues_view_zip")
        .partial(
            left=combine_landdx_speed_layers,
            right=zoom_traj_view,
            **(params_dict.get("speedvalues_view_zip") or {}),
        )
        .call()
    )

    draw_speed_ecomaps = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_speed_ecomaps")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Speed Values(Km/h)"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_speed_ecomaps") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=speedvalues_view_zip
        )
    )

    persist_speed_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_speed_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_speed_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_speed_ecomaps)
    )

    create_speed_ecomap_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_speed_ecomap_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Speedmap", **(params_dict.get("create_speed_ecomap_widgets") or {})
        )
        .map(argnames=["view", "data"], argvalues=persist_speed_ecomap_urls)
    )

    merge_speed_ecomap_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_speed_ecomap_widgets")
        .partial(
            widgets=create_speed_ecomap_widgets,
            **(params_dict.get("merge_speed_ecomap_widgets") or {}),
        )
        .call()
    )

    sort_trajectories_by_day_night = (
        sort_values.validate()
        .handle_errors(task_instance_id="sort_trajectories_by_day_night")
        .partial(
            column_name="extra__is_night",
            ascending=False,
            na_position="last",
            **(params_dict.get("sort_trajectories_by_day_night") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    apply_day_night_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_day_night_colormap")
        .partial(
            colormap=["#292965", "#e7a553"],
            input_column_name="extra__is_night",
            output_column_name="day_night_colors",
            **(params_dict.get("apply_day_night_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_trajectories_by_day_night)
    )

    generate_day_night_ecomap_layers = (
        create_polyline_layer.validate()
        .handle_errors(task_instance_id="generate_day_night_ecomap_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "day_night_colors"},
            legend={"labels": ["Night", "Day"], "colors": ["#292965", "#e7a553"]},
            tooltip_columns=["extra__is_night", "extra__name", "extra__sex"],
            **(params_dict.get("generate_day_night_ecomap_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_day_night_colormap)
    )

    zoom_dn_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_dn_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_dn_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=apply_day_night_colormap)
    )

    combine_landdx_dn_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="combine_landdx_dn_layers")
        .partial(
            static_layers=create_styled_landdx_layers,
            **(params_dict.get("combine_landdx_dn_layers") or {}),
        )
        .mapvalues(
            argnames=["grouped_layers"], argvalues=generate_day_night_ecomap_layers
        )
    )

    dn_view_zip = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="dn_view_zip")
        .partial(
            left=combine_landdx_dn_layers,
            right=zoom_dn_view,
            **(params_dict.get("dn_view_zip") or {}),
        )
        .call()
    )

    draw_day_night_ecomaps = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_day_night_ecomaps")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Day-Night Tracks"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_day_night_ecomaps") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=dn_view_zip)
    )

    persist_day_night_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_day_night_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_day_night_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_day_night_ecomaps)
    )

    create_day_night_ecomap_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_day_night_ecomap_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Day/Night Ecomap",
            **(params_dict.get("create_day_night_ecomap_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_day_night_ecomap_urls)
    )

    merge_day_night_ecomap_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_day_night_ecomap_widgets")
        .partial(
            widgets=create_day_night_ecomap_widgets,
            **(params_dict.get("merge_day_night_ecomap_widgets") or {}),
        )
        .call()
    )

    sort_trajs_by_quarter_status = (
        sort_values.validate()
        .handle_errors(task_instance_id="sort_trajs_by_quarter_status")
        .partial(
            column_name="quarter_status",
            ascending=False,
            na_position="last",
            **(params_dict.get("sort_trajs_by_quarter_status") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    apply_quarter_status_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_quarter_status_colormap")
        .partial(
            colormap=["#2f4f4f", "#ff8c00"],
            input_column_name="quarter_status",
            output_column_name="quarter_status_colors",
            **(params_dict.get("apply_quarter_status_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_trajs_by_quarter_status)
    )

    generate_quarter_ecomap_layers = (
        create_polyline_layer.validate()
        .handle_errors(task_instance_id="generate_quarter_ecomap_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"color_column": "quarter_status_colors"},
            legend={
                "labels": ["Previous Quarter", "Current Quarter"],
                "colors": ["#2f4f4f", "#ff8c00"],
            },
            tooltip_columns=[
                "extra__is_night",
                "extra__name",
                "extra__sex",
                "quarter_status",
                "day_night_colors",
            ],
            **(params_dict.get("generate_quarter_ecomap_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_quarter_status_colormap)
    )

    zoom_qm_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_qm_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_qm_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=format_speed_values)
    )

    combine_quarter_ecomap_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="combine_quarter_ecomap_layers")
        .partial(
            static_layers=create_styled_landdx_layers,
            **(params_dict.get("combine_quarter_ecomap_layers") or {}),
        )
        .mapvalues(
            argnames=["grouped_layers"], argvalues=generate_quarter_ecomap_layers
        )
    )

    qm_view_zip = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="qm_view_zip")
        .partial(
            left=combine_quarter_ecomap_layers,
            right=zoom_qm_view,
            **(params_dict.get("qm_view_zip") or {}),
        )
        .call()
    )

    draw_quarter_status_ecomaps = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_quarter_status_ecomaps")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={
                "placement": "bottom-right",
                "title": "Quarter Movement Tracks",
            },
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_quarter_status_ecomaps") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=qm_view_zip)
    )

    persist_quarter_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_quarter_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_quarter_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_quarter_status_ecomaps)
    )

    create_quarter_ecomap_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_quarter_ecomap_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Subject Group Quarter Movement Map",
            **(params_dict.get("create_quarter_ecomap_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_quarter_ecomap_urls)
    )

    merge_quarter_ecomap_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_quarter_ecomap_widgets")
        .partial(
            widgets=create_quarter_ecomap_widgets,
            **(params_dict.get("merge_quarter_ecomap_widgets") or {}),
        )
        .call()
    )

    generate_etd = (
        calculate_etd_by_groups.validate()
        .handle_errors(task_instance_id="generate_etd")
        .partial(
            crs="ESRI:53042",
            percentiles=[50.0, 60.0, 70.0, 80.0, 90.0, 95.0, 99.0],
            nodata_value="nan",
            band_count=1,
            include_groups=True,
            groupby_cols=["season"],
            **(params_dict.get("generate_etd") or {}),
        )
        .mapvalues(argnames=["trajectory_gdf"], argvalues=split_trajectories_by_group)
    )

    calculate_mcp = (
        generate_mcp_gdf.validate()
        .handle_errors(task_instance_id="calculate_mcp")
        .partial(planar_crs="ESRI:102022", **(params_dict.get("calculate_mcp") or {}))
        .mapvalues(argnames=["gdf"], argvalues=split_trajectories_by_group)
    )

    apply_etd_percentile_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_etd_percentile_colormap")
        .partial(
            input_column_name="percentile",
            colormap="RdYlGn",
            output_column_name="percentile_colormap",
            **(params_dict.get("apply_etd_percentile_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=generate_etd)
    )

    generate_etd_ecomap_layers = (
        create_polygon_layer.validate()
        .handle_errors(task_instance_id="generate_etd_ecomap_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "percentile_colormap", "opacity": 0.55},
            legend={
                "label_column": "percentile",
                "color_column": "percentile_colormap",
            },
            tooltip_columns=["percentile"],
            **(params_dict.get("generate_etd_ecomap_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=apply_etd_percentile_colormap)
    )

    generate_mcp_layers = (
        create_polygon_layer.validate()
        .handle_errors(task_instance_id="generate_mcp_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "get_fill_color": "#FFFFFF00",
                "get_line_color": "#dc143c",
                "opacity": 0.55,
                "stroked": True,
            },
            legend={"labels": ["mcp"], "colors": ["#dc143c"]},
            tooltip_columns=["area_km2"],
            **(params_dict.get("generate_mcp_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=calculate_mcp)
    )

    zoom_hr_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_hr_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_hr_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=apply_etd_percentile_colormap)
    )

    zip_mcp_hr = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="zip_mcp_hr")
        .partial(
            left=generate_mcp_layers,
            right=generate_etd_ecomap_layers,
            **(params_dict.get("zip_mcp_hr") or {}),
        )
        .call()
    )

    combine_landdx_hr_ecomap_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="combine_landdx_hr_ecomap_layers")
        .partial(
            static_layers=create_styled_landdx_layers,
            **(params_dict.get("combine_landdx_hr_ecomap_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=zip_mcp_hr)
    )

    hr_view_zip = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="hr_view_zip")
        .partial(
            left=combine_landdx_hr_ecomap_layers,
            right=zoom_hr_view,
            **(params_dict.get("hr_view_zip") or {}),
        )
        .call()
    )

    draw_hr_ecomaps = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_hr_ecomaps")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Home Range Metrics"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_hr_ecomaps") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=hr_view_zip)
    )

    persist_hr_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="persist_hr_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("persist_hr_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_hr_ecomaps)
    )

    create_hr_ecomap_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="create_hr_ecomap_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Home Range Ecomap",
            **(params_dict.get("create_hr_ecomap_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=persist_hr_ecomap_urls)
    )

    merge_hr_ecomap_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="merge_hr_ecomap_widgets")
        .partial(
            widgets=create_hr_ecomap_widgets,
            **(params_dict.get("merge_hr_ecomap_widgets") or {}),
        )
        .call()
    )

    generate_speed_raster = (
        generate_ecograph_raster.validate()
        .handle_errors(task_instance_id="generate_speed_raster")
        .partial(
            dist_col="dist_meters",
            interpolation="mean",
            movement_covariate="speed",
            output_dir=create_output_directory,
            **(params_dict.get("generate_speed_raster") or {}),
        )
        .mapvalues(argnames=["gdf"], argvalues=split_trajectories_by_group)
    )

    extract_speed_rasters = (
        retrieve_feature_gdf.validate()
        .handle_errors(task_instance_id="extract_speed_rasters")
        .partial(**(params_dict.get("extract_speed_rasters") or {}))
        .mapvalues(argnames=["file_path"], argvalues=generate_speed_raster)
    )

    sort_speed_features_by_value = (
        sort_values.validate()
        .handle_errors(task_instance_id="sort_speed_features_by_value")
        .partial(
            column_name="value",
            na_position="last",
            **(params_dict.get("sort_speed_features_by_value") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=extract_speed_rasters)
    )

    classify_speed_features = (
        apply_classification.validate()
        .handle_errors(task_instance_id="classify_speed_features")
        .partial(
            input_column_name="value",
            output_column_name="bins",
            classification_options={"scheme": "natural_breaks", "k": 6},
            label_options={"label_ranges": False, "label_decimals": 1},
            **(params_dict.get("classify_speed_features") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=sort_speed_features_by_value)
    )

    apply_speed_raster_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="apply_speed_raster_colormap")
        .partial(
            input_column_name="bins",
            output_column_name="speedraster_bins_colors",
            colormap=["#1a9850", "#91cf60", "#d9ef8b", "#fee08b", "#fc8d59", "#d73027"],
            **(params_dict.get("apply_speed_raster_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=classify_speed_features)
    )

    format_speed_raster_labels = (
        map_values_with_unit.validate()
        .handle_errors(task_instance_id="format_speed_raster_labels")
        .partial(
            input_column_name="bins",
            output_column_name="bins_formatted",
            original_unit="km/h",
            new_unit="km/h",
            decimal_places=1,
            **(params_dict.get("format_speed_raster_labels") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=apply_speed_raster_colormap)
    )

    generate_raster_layers = (
        create_polygon_layer.validate()
        .handle_errors(task_instance_id="generate_raster_layers")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={
                "fill_color_column": "speedraster_bins_colors",
                "opacity": 0.55,
            },
            legend={
                "label_column": "bins_formatted",
                "color_column": "speedraster_bins_colors",
            },
            tooltip_columns=["value", "bins", "speedraster_bins_colors"],
            **(params_dict.get("generate_raster_layers") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=format_speed_raster_labels)
    )

    zoom_speedraster_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_speedraster_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_speedraster_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=format_speed_raster_labels)
    )

    combine_seasonal_raster_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="combine_seasonal_raster_layers")
        .partial(
            static_layers=create_styled_landdx_layers,
            **(params_dict.get("combine_seasonal_raster_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=generate_raster_layers)
    )

    speedraster_view_zip = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="speedraster_view_zip")
        .partial(
            left=combine_seasonal_raster_layers,
            right=zoom_speedraster_view,
            **(params_dict.get("speedraster_view_zip") or {}),
        )
        .call()
    )

    draw_speed_raster_ecomaps = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="draw_speed_raster_ecomaps")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Raster Value(Km/h)"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("draw_speed_raster_ecomaps") or {}),
        )
        .mapvalues(
            argnames=["geo_layers", "view_state"], argvalues=speedraster_view_zip
        )
    )

    speed_raster_ecomap_urls = (
        persist_text.validate()
        .handle_errors(task_instance_id="speed_raster_ecomap_urls")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("speed_raster_ecomap_urls") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=draw_speed_raster_ecomaps)
    )

    speed_raster_ecomap_widgets = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="speed_raster_ecomap_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Speed Raster Ecomap",
            **(params_dict.get("speed_raster_ecomap_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=speed_raster_ecomap_urls)
    )

    speedraster_ecomap_widgets = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="speedraster_ecomap_widgets")
        .partial(
            widgets=speed_raster_ecomap_widgets,
            **(params_dict.get("speedraster_ecomap_widgets") or {}),
        )
        .call()
    )

    season_colormap = (
        apply_color_map.validate()
        .handle_errors(task_instance_id="season_colormap")
        .partial(
            input_column_name="season",
            output_column_name="season_colormap",
            colormap=["#f57c00", "#4cf3f7"],
            **(params_dict.get("season_colormap") or {}),
        )
        .mapvalues(argnames=["df"], argvalues=generate_etd)
    )

    season_etd_map_layer = (
        create_polygon_layer.validate()
        .handle_errors(task_instance_id="season_etd_map_layer")
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            layer_style={"fill_color_column": "season_colormap", "opacity": 0.65},
            legend={"label_column": "season", "color_column": "season_colormap"},
            tooltip_columns=["percentile"],
            **(params_dict.get("season_etd_map_layer") or {}),
        )
        .mapvalues(argnames=["geodataframe"], argvalues=season_colormap)
    )

    zoom_season_view = (
        create_view_state_from_gdf.validate()
        .handle_errors(task_instance_id="zoom_season_view")
        .partial(pitch=0, bearing=0, **(params_dict.get("zoom_season_view") or {}))
        .mapvalues(argnames=["gdf"], argvalues=season_colormap)
    )

    comb_season_map_layers = (
        combine_map_layers.validate()
        .handle_errors(task_instance_id="comb_season_map_layers")
        .partial(
            static_layers=create_styled_landdx_layers,
            **(params_dict.get("comb_season_map_layers") or {}),
        )
        .mapvalues(argnames=["grouped_layers"], argvalues=season_etd_map_layer)
    )

    seasons_view_zip = (
        zip_grouped_by_key.validate()
        .handle_errors(task_instance_id="seasons_view_zip")
        .partial(
            left=comb_season_map_layers,
            right=zoom_season_view,
            **(params_dict.get("seasons_view_zip") or {}),
        )
        .call()
    )

    seasonal_ecomap = (
        draw_ecomap.validate()
        .handle_errors(task_instance_id="seasonal_ecomap")
        .partial(
            tile_layers=configure_base_maps,
            north_arrow_style={"placement": "top-left"},
            legend_style={"placement": "bottom-right", "title": "Seasons"},
            static=False,
            title=None,
            max_zoom=20,
            **(params_dict.get("seasonal_ecomap") or {}),
        )
        .mapvalues(argnames=["geo_layers", "view_state"], argvalues=seasons_view_zip)
    )

    season_etd_ecomap_html_url = (
        persist_text.validate()
        .handle_errors(task_instance_id="season_etd_ecomap_html_url")
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params_dict.get("season_etd_ecomap_html_url") or {}),
        )
        .mapvalues(argnames=["text"], argvalues=seasonal_ecomap)
    )

    season_etd_widgets_single_view = (
        create_map_widget_single_view.validate()
        .handle_errors(task_instance_id="season_etd_widgets_single_view")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Subject Group Home Range Map (Seasons)",
            **(params_dict.get("season_etd_widgets_single_view") or {}),
        )
        .map(argnames=["view", "data"], argvalues=season_etd_ecomap_html_url)
    )

    season_grouped_map_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="season_grouped_map_widget")
        .partial(
            widgets=season_etd_widgets_single_view,
            **(params_dict.get("season_grouped_map_widget") or {}),
        )
        .call()
    )

    total_mcp_area = (
        dataframe_column_sum.validate()
        .handle_errors(task_instance_id="total_mcp_area")
        .partial(column_name="area_km2", **(params_dict.get("total_mcp_area") or {}))
        .mapvalues(argnames=["df"], argvalues=calculate_mcp)
    )

    total_grid_area = (
        dataframe_column_sum.validate()
        .handle_errors(task_instance_id="total_grid_area")
        .partial(column_name="area_sqkm", **(params_dict.get("total_grid_area") or {}))
        .mapvalues(argnames=["df"], argvalues=generate_etd)
    )

    total_mcp_sv_widgets = (
        create_single_value_widget_single_view.validate()
        .handle_errors(task_instance_id="total_mcp_sv_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total MCP Area",
            decimal_places=1,
            **(params_dict.get("total_mcp_sv_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_mcp_area)
    )

    total_mcp_grouped_sv_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="total_mcp_grouped_sv_widget")
        .partial(
            widgets=total_mcp_sv_widgets,
            **(params_dict.get("total_mcp_grouped_sv_widget") or {}),
        )
        .call()
    )

    total_grid_sv_widgets = (
        create_single_value_widget_single_view.validate()
        .handle_errors(task_instance_id="total_grid_sv_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Total Grid Area",
            decimal_places=1,
            **(params_dict.get("total_grid_sv_widgets") or {}),
        )
        .map(argnames=["view", "data"], argvalues=total_grid_area)
    )

    total_grid_grouped_sv_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="total_grid_grouped_sv_widget")
        .partial(
            widgets=total_grid_sv_widgets,
            **(params_dict.get("total_grid_grouped_sv_widget") or {}),
        )
        .call()
    )

    subject_gender = (
        dataframe_column_first_unique_str.validate()
        .handle_errors(task_instance_id="subject_gender")
        .partial(column_name="extra__sex", **(params_dict.get("subject_gender") or {}))
        .mapvalues(argnames=["df"], argvalues=split_trajectories_by_group)
    )

    gender_widgets = (
        create_text_widget_single_view.validate()
        .handle_errors(task_instance_id="gender_widgets")
        .skipif(
            conditions=[
                never,
            ],
            unpack_depth=1,
        )
        .partial(title="Gender", **(params_dict.get("gender_widgets") or {}))
        .map(argnames=["view", "data"], argvalues=subject_gender)
    )

    gender_sv_widget = (
        merge_widget_views.validate()
        .handle_errors(task_instance_id="gender_sv_widget")
        .partial(widgets=gender_widgets, **(params_dict.get("gender_sv_widget") or {}))
        .call()
    )

    mapbook_dashboard = (
        gather_dashboard.validate()
        .handle_errors(task_instance_id="mapbook_dashboard")
        .partial(
            details=initialize_workflow_metadata,
            widgets=[
                gender_sv_widget,
                total_mcp_grouped_sv_widget,
                total_grid_grouped_sv_widget,
                merge_speed_ecomap_widgets,
                merge_day_night_ecomap_widgets,
                merge_quarter_ecomap_widgets,
                merge_hr_ecomap_widgets,
                speedraster_ecomap_widgets,
                season_grouped_map_widget,
            ],
            time_range=define_time_range,
            groupers=configure_grouping_strategy,
            **(params_dict.get("mapbook_dashboard") or {}),
        )
        .call()
    )

    return mapbook_dashboard
