"""Wraps the sequential CLI with resource sampling and trace parsing.

Generated by dev/recompile.sh; do not edit by hand.
"""

import importlib.util
import os
import subprocess
import sys
from pathlib import Path


def _patch_wt_task_tracing() -> None:
    # Defer wt_task's GCP-only CloudTraceSpanExporter import so TRACING_AVAILABLE=True
    # without the optional opentelemetry-exporter-gcp-trace package. pixi re-installs
    # packages on env refresh, so we re-apply this every run.
    try:
        spec = importlib.util.find_spec("wt_task.tracing._config")
    except ImportError:
        return
    if spec is None or not spec.origin:
        return
    p = Path(spec.origin)
    text = p.read_text()
    old_import = "    from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter\n"
    old_case = (
        '            case "gcp":\n'
        "                _exporter = CloudTraceSpanExporter(**_exporter_kws)  # type: ignore[no-untyped-call]\n"
    )
    new_case = (
        '            case "gcp":\n'
        "                from opentelemetry.exporter.cloud_trace import CloudTraceSpanExporter  # noqa: PLC0415\n"
        "                _exporter = CloudTraceSpanExporter(**_exporter_kws)  # type: ignore[no-untyped-call]\n"
    )
    if old_import not in text:
        return
    text = text.replace(old_import, "").replace(old_case, new_case)
    p.write_text(text)
    pyc = Path(importlib.util.cache_from_source(str(p)))
    pyc.unlink(missing_ok=True)


def main() -> int:
    _patch_wt_task_tracing()

    script_dir = Path(__file__).resolve().parent
    cli_cmd = [sys.executable, "-m", "ecoscope_workflows_general_report_workflow.cli", *sys.argv[1:]]

    results_url = os.environ.get("ECOSCOPE_WORKFLOWS_RESULTS", "")
    rp = results_url[len("file://"):] if results_url.startswith("file://") else results_url

    if rp:
        ec = subprocess.call(
            [sys.executable, str(script_dir / "resource-sampler.py"), rp, *cli_cmd]
        )
        traces = Path(rp) / "otel_traces.jsonl"
        if traces.is_file():
            subprocess.call([sys.executable, str(script_dir / "parse-traces.py"), str(traces)])
        return ec
    else:
        return subprocess.call(cli_cmd)


if __name__ == "__main__":
    sys.exit(main())
