workflow_details:
  description: ''
  name: Custom_general_workflow
time_range:
  timezone:
    label: UTC
    tzCode: UTC
    name: UTC
    utc: '+03:00'
  time_format: '%d %b %Y %H:%M:%S'
  since: '2025-12-31T21:00:00.000Z'
  until: '2026-02-22T21:00:00.000Z'
set_previous_period:
  option:
    custom: Previous 3 months
er_client_name:
  data_source:
    name: ymep
gee_project_name:
  data_source:
    name: ecoscope_poc
subject_group_var:
  var: MEP_Elephants_Amboseli
retrieve_ldx_db:
  input_method:
    file_path: /Users/tevintemu/Desktop/Ecoscope/shapefiles/landDx.gpkg
custom_trajs_filter:
  min_length_meters: 0.001
  max_length_meters: 5000
  min_time_secs: 1
  max_time_secs: 21600
  min_speed_kmhr: 0.01
  max_speed_kmhr: 9
get_events_data:
  event_types:
    - mep_elephant_sighting
logo_path:
  input_method:
    file_path: /Users/tevintemu/Desktop/save-the-elephants.jpg
