workflow_details:
  description: ''
  name: custom
time_range:
  timezone:
    utc: '+00:00'
    name: UTC
    tzCode: UTC
    label: UTC
  time_format: '%d %b %Y %H:%M:%S'
  since: '2025-05-01T09:40:00.000Z'
  until: '2026-02-02T09:40:00.000Z'
groupers:
  groupers:
    - subject_name
configure_base_maps:
  base_maps:
    - url: >-
        https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}
      opacity: 1
      max_zoom: 20
set_previous_period:
  option:
    time_range:
      timezone:
        label: UTC
        tzCode: UTC
        name: UTC
        utc: '+00:00'
      time_format: '%d %b %Y %H:%M:%S'
      since: '2024-09-01T09:40:00.000Z'
er_client_name:
  data_source:
    name: ate
gee_project_name:
  data_source:
    name: ecoscope_poc
retrieve_ldx_db:
  input_method:
    file_path: /Users/tevintemu/Desktop/Ecoscope/shapefiles/landDx.gpkg
custom_trajs_filter:
  min_length_meters: 0.001
  max_length_meters: 5000
  min_time_secs: 1
  max_time_secs: 21600
  min_speed_kmhr: 0.01
  max_speed_kmhr: 9
logo_path:
  input_method:
    file_path: /Users/tevintemu/Desktop/logo.png
subject_group_var:
  var: Elephants - STE
