workflow_details:
  description: ''
  name: sef
time_range:
  timezone:
    label: UTC
    tzCode: UTC
    name: UTC
    utc: '+03:00'
  time_format: '%d %b %Y %H:%M:%S'
  since: '2026-01-01T17:59:00.000Z'
  until: '2026-02-16T17:59:00.000Z'
groupers:
  groupers:
    - index_name: subject_name
set_previous_period:
  option:
    custom: Same as current period
er_client_name:
  data_source:
    name: ste
gee_project_name:
  data_source:
    name: ecoscope_poc
subject_group_var:
  var: ecoscope
retrieve_ldx_db:
  input_method:
    file_path: /Users/tevintemu/Desktop/Ecoscope/shapefiles/landDx.gpkg
custom_trajs_filter:
  min_length_meters: 0.001
  max_length_meters: 5000
  min_time_secs: 1
  max_time_secs: 21600
  min_speed_kmhr: 0.01
  max_speed_kmhr: 9
zoom_to_envelope:
  expansion_factor: 1.05
logo_path:
  input_method:
    file_path: /Users/tevintemu/Desktop/logo.png
