name: 'Setup Pixi'
description: 'Install Pixi package manager'
inputs:
  pixi-version:
    description: 'Version of Pixi to install'
    required: false
    default: 'latest'
runs:
  using: 'composite'
  steps:
    - name: Install pixi
      shell: bash
      run: curl -fsSL https://pixi.sh/install.sh | bash && echo "$HOME/.pixi/bin" >> $GITHUB_PATH
