# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Aerial Survey Lines
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers as set_groupers
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ste.tasks import (
    combine_deckgl_map_layers as combine_deckgl_map_layers,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_deckgl_layer_from_gdf as create_deckgl_layer_from_gdf,
)
from ecoscope_workflows_ext_ste.tasks import draw_survey_lines as draw_survey_lines
from ecoscope_workflows_ext_ste.tasks import get_file_path as get_file_path
from ecoscope_workflows_ext_ste.tasks import get_gdf_geom_type as get_gdf_geom_type
from ecoscope_workflows_ext_ste.tasks import transform_gdf_crs as transform_gdf_crs
from ecoscope_workflows_ext_ste.tasks import view_state_deck_gdf as view_state_deck_gdf

# %% [markdown]
# ## Set workflow details

# %%
# parameters

workflow_details_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


workflow_details = (
    set_workflow_details.set_task_instance_id("workflow_details")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**workflow_details_params)
    .call()
)


# %% [markdown]
# ## Time range

# %%
# parameters

time_range_params = dict()

# %%
# call the task


time_range = (
    set_time_range.set_task_instance_id("time_range")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        time_format="%d %b %Y %H:%M:%S %Z",
        timezone={
            "label": "UTC",
            "tzCode": "UTC",
            "name": "UTC",
            "utc_offset": "+03:00",
        },
        since="2026-01-01T00:00:00Z",
        until="2026-02-28T23:59:59Z",
        **time_range_params,
    )
    .call()
)


# %% [markdown]
# ## Set groupers

# %%
# parameters

groupers_params = dict()

# %%
# call the task


groupers = (
    set_groupers.set_task_instance_id("groupers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(groupers=[], **groupers_params)
    .call()
)


# %% [markdown]
# ## Configure base map layers

# %%
# parameters

configure_base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


configure_base_maps = (
    set_base_maps_pydeck.set_task_instance_id("configure_base_maps")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(**configure_base_maps_params)
    .call()
)


# %% [markdown]
# ## Retrieve input from get shapefile

# %%
# parameters

retrieve_file_params_params = dict(
    input_method=...,
)

# %%
# call the task


retrieve_file_params = (
    get_file_path.set_task_instance_id("retrieve_file_params")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **retrieve_file_params_params,
    )
    .call()
)


# %% [markdown]
# ## load gdf

# %%
# parameters

load_gdf_params = dict()

# %%
# call the task


load_gdf = (
    load_df.set_task_instance_id("load_gdf")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        file_path=retrieve_file_params,
        layer=None,
        deserialize_json=False,
        **load_gdf_params,
    )
    .call()
)


# %% [markdown]
# ## Assign geom type to gdf

# %%
# parameters

assign_geom_type_params = dict()

# %%
# call the task


assign_geom_type = (
    get_gdf_geom_type.set_task_instance_id("assign_geom_type")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=load_gdf, **assign_geom_type_params)
    .call()
)


# %% [markdown]
# ## Generate layers for map

# %%
# parameters

generate_layers_map_params = dict()

# %%
# call the task


generate_layers_map = (
    create_deckgl_layer_from_gdf.set_task_instance_id("generate_layers_map")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        gdf=assign_geom_type,
        style={
            "get_fill_color": [85, 107, 47],
            "get_line_color": [85, 107, 47],
            "opacity": 0.15,
            "stroked": True,
            "get_line_width": 1.25,
        },
        legend={
            "title": "Legend",
            "values": [{"label": "Area of Interest", "color": "#556b2f"}],
        },
        **generate_layers_map_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Aerial Survey Lines

# %%
# parameters

survey_lines_params = dict(
    direction=...,
    spacing=...,
)

# %%
# call the task


survey_lines = (
    draw_survey_lines.set_task_instance_id("survey_lines")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=load_gdf, **survey_lines_params)
    .call()
)


# %% [markdown]
# ## Persist aerial survey as geopackage

# %%
# parameters

persist_aerial_gdf_params = dict()

# %%
# call the task


persist_aerial_gdf = (
    persist_df.set_task_instance_id("persist_aerial_gdf")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        filetype="gpkg",
        filename="aerial_survey",
        df=survey_lines,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_aerial_gdf_params,
    )
    .call()
)


# %% [markdown]
# ## Persist aerial survey as geoparquet

# %%
# parameters

persist_aerial_gpq_params = dict()

# %%
# call the task


persist_aerial_gpq = (
    persist_df.set_task_instance_id("persist_aerial_gpq")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        filetype="geoparquet",
        filename="aerial_survey",
        df=survey_lines,
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_aerial_gpq_params,
    )
    .call()
)


# %% [markdown]
# ## Transform gdf to epsg 4326

# %%
# parameters

transform_gdf_params = dict()

# %%
# call the task


transform_gdf = (
    transform_gdf_crs.set_task_instance_id("transform_gdf")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(gdf=survey_lines, crs="EPSG:4326", **transform_gdf_params)
    .call()
)


# %% [markdown]
# ## Create Aerial Survey Lines

# %%
# parameters

aerial_survey_polylines_params = dict()

# %%
# call the task


aerial_survey_polylines = (
    create_geojson_layer.set_task_instance_id("aerial_survey_polylines")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        layer_style={
            "filled": False,
            "stroked": True,
            "extruded": False,
            "wireframe": False,
            "get_fill_color": [255, 265, 0],
            "get_line_color": [255, 265, 0],
            "opacity": 0.85,
            "get_line_width": 1.55,
            "get_elevation": 0,
            "get_point_radius": 1,
            "line_width_units": "pixels",
            "line_width_scale": 1,
            "line_width_min_pixels": 1,
            "line_width_max_pixels": 5,
        },
        legend={"title": "", "values": [{"label": "Aerial lines", "color": "#ffa500"}]},
        geodataframe=transform_gdf,
        **aerial_survey_polylines_params,
    )
    .call()
)


# %% [markdown]
# ## Zoom to gdf extent

# %%
# parameters

zoom_gdf_extent_params = dict()

# %%
# call the task


zoom_gdf_extent = (
    view_state_deck_gdf.set_task_instance_id("zoom_gdf_extent")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(pitch=0, bearing=0, gdf=load_gdf, **zoom_gdf_extent_params)
    .call()
)


# %% [markdown]
# ## Combine generated aerial survey lines with custom gdf

# %%
# parameters

combine_map_layers_params = dict()

# %%
# call the task


combine_map_layers = (
    combine_deckgl_map_layers.set_task_instance_id("combine_map_layers")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        static_layers=[generate_layers_map],
        grouped_layers=[aerial_survey_polylines],
        **combine_map_layers_params,
    )
    .call()
)


# %% [markdown]
# ## Draw Aerial Survey Lines Ecomap

# %%
# parameters

draw_aerial_survey_lines_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_aerial_survey_lines_ecomap = (
    draw_map.set_task_instance_id("draw_aerial_survey_lines_ecomap")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        title=None,
        max_zoom=10,
        legend_style={"placement": "bottom-right"},
        geo_layers=combine_map_layers,
        view_state=zoom_gdf_extent,
        **draw_aerial_survey_lines_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Ecomaps

# %%
# parameters

persist_ecomaps_params = dict(
    filename_suffix=...,
)

# %%
# call the task


persist_ecomaps = (
    persist_text.set_task_instance_id("persist_ecomaps")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_aerial_survey_lines_ecomap,
        filename="aerial_survey.html",
        **persist_ecomaps_params,
    )
    .call()
)


# %% [markdown]
# ## Create Ecomap Widgets

# %%
# parameters

create_aerial_widgets_params = dict(
    view=...,
)

# %%
# call the task


create_aerial_widgets = (
    create_map_widget_single_view.set_task_instance_id("create_aerial_widgets")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        title="Aerial Survey Lines",
        data=persist_ecomaps,
        **create_aerial_widgets_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard with Patrol Map Widgets

# %%
# parameters

patrol_dashboard_params = dict(
    warning=...,
)

# %%
# call the task


patrol_dashboard = (
    gather_dashboard.set_task_instance_id("patrol_dashboard")
    .handle_errors()
    .with_tracing()
    .skipif(
        conditions=[
            any_is_empty_df,
            any_dependency_skipped,
        ],
        unpack_depth=1,
    )
    .partial(
        details=workflow_details,
        widgets=create_aerial_widgets,
        time_range=time_range,
        groupers=groupers,
        **patrol_dashboard_params,
    )
    .call()
)
