# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details


# ruff: noqa: E402

# %% [markdown]
# # Aerial Survey Lines
# TODO: top level description

# %% [markdown]
# ## Imports

import os

from ecoscope_workflows_core.tasks.config import set_workflow_details
from ecoscope_workflows_core.tasks.filter import set_time_range
from ecoscope_workflows_core.tasks.groupby import set_groupers
from ecoscope_workflows_core.tasks.io import persist_text
from ecoscope_workflows_core.tasks.results import (
    create_map_widget_single_view,
    gather_dashboard,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import download_roi, persist_df
from ecoscope_workflows_ext_ecoscope.tasks.results import (
    create_polyline_layer,
    draw_ecomap,
    set_base_maps,
)
from ecoscope_workflows_ext_ste.tasks import (
    create_view_state_from_gdf,
    generate_survey_lines,
)

# %% [markdown]
# ## Initialize Workflow Metadata

# %%
# parameters

initialize_workflow_metadata_params = dict(
    name=...,
    description=...,
    image_url=...,
)

# %%
# call the task


initialize_workflow_metadata = (
    set_workflow_details.handle_errors(task_instance_id="initialize_workflow_metadata")
    .partial(**initialize_workflow_metadata_params)
    .call()
)


# %% [markdown]
# ## Define Time Range

# %%
# parameters

define_time_range_params = dict(
    since=...,
    until=...,
    timezone=...,
)

# %%
# call the task


define_time_range = (
    set_time_range.handle_errors(task_instance_id="define_time_range")
    .partial(time_format="%d %b %Y %H:%M:%S %Z", **define_time_range_params)
    .call()
)


# %% [markdown]
# ## Configure Grouping Strategy

# %%
# parameters

configure_grouping_strategy_params = dict(
    groupers=...,
)

# %%
# call the task


configure_grouping_strategy = (
    set_groupers.handle_errors(task_instance_id="configure_grouping_strategy")
    .partial(**configure_grouping_strategy_params)
    .call()
)


# %% [markdown]
# ## Configure Base Map Layers

# %%
# parameters

configure_base_maps_params = dict(
    base_maps=...,
)

# %%
# call the task


configure_base_maps = (
    set_base_maps.handle_errors(task_instance_id="configure_base_maps")
    .partial(**configure_base_maps_params)
    .call()
)


# %% [markdown]
# ## Download Region of Interest (ROI)

# %%
# parameters

fetch_roi_layer_params = dict(
    url=...,
)

# %%
# call the task


fetch_roi_layer = (
    download_roi.handle_errors(task_instance_id="fetch_roi_layer")
    .partial(roi_column=None, roi_name=None, layer_name=None, **fetch_roi_layer_params)
    .call()
)


# %% [markdown]
# ## Draw Aerial Survey Lines

# %%
# parameters

draw_survey_lines_params = dict(
    direction=...,
    spacing=...,
)

# %%
# call the task


draw_survey_lines = (
    generate_survey_lines.handle_errors(task_instance_id="draw_survey_lines")
    .partial(gdf=fetch_roi_layer, **draw_survey_lines_params)
    .call()
)


# %% [markdown]
# ## Persist Aerial Survey as Geopackage

# %%
# parameters

persist_aerial_gdf_params = dict(
    filename=...,
)

# %%
# call the task


persist_aerial_gdf = (
    persist_df.handle_errors(task_instance_id="persist_aerial_gdf")
    .partial(
        df=draw_survey_lines,
        filetype="gpkg",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_aerial_gdf_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Aerial Survey as Geoparquet

# %%
# parameters

persist_aerial_geoparquet_params = dict(
    filename=...,
)

# %%
# call the task


persist_aerial_geoparquet = (
    persist_df.handle_errors(task_instance_id="persist_aerial_geoparquet")
    .partial(
        df=draw_survey_lines,
        filetype="geoparquet",
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        **persist_aerial_geoparquet_params,
    )
    .call()
)


# %% [markdown]
# ## Create Aerial Survey Lines

# %%
# parameters

aerial_survey_polylines_params = dict(
    tooltip_columns=...,
    zoom=...,
)

# %%
# call the task


aerial_survey_polylines = (
    create_polyline_layer.handle_errors(task_instance_id="aerial_survey_polylines")
    .partial(
        layer_style={
            "get_width": 1.5,
            "get_color": "#2f4f4f",
            "opacity": 0.85,
            "width_unit": "pixels",
        },
        legend={"labels": ["Aerial survey lines"], "colors": ["#2f4f4f"]},
        geodataframe=draw_survey_lines,
        **aerial_survey_polylines_params,
    )
    .call()
)


# %% [markdown]
# ## zoom by view state

# %%
# parameters

zoom_view_state_params = dict()

# %%
# call the task


zoom_view_state = (
    create_view_state_from_gdf.handle_errors(task_instance_id="zoom_view_state")
    .partial(pitch=0, bearing=0, gdf=draw_survey_lines, **zoom_view_state_params)
    .call()
)


# %% [markdown]
# ## Draw Aerial Survey Lines Ecomap

# %%
# parameters

draw_aerial_survey_lines_ecomap_params = dict(
    widget_id=...,
)

# %%
# call the task


draw_aerial_survey_lines_ecomap = (
    draw_ecomap.handle_errors(task_instance_id="draw_aerial_survey_lines_ecomap")
    .partial(
        tile_layers=configure_base_maps,
        static=False,
        max_zoom=12,
        north_arrow_style={"placement": "top-left"},
        legend_style={"placement": "bottom-right", "title": "Aerial survey lines"},
        title=None,
        geo_layers=aerial_survey_polylines,
        view_state=zoom_view_state,
        **draw_aerial_survey_lines_ecomap_params,
    )
    .call()
)


# %% [markdown]
# ## Persist Ecomaps

# %%
# parameters

persist_ecomaps_params = dict(
    filename=...,
    filename_suffix=...,
)

# %%
# call the task


persist_ecomaps = (
    persist_text.handle_errors(task_instance_id="persist_ecomaps")
    .partial(
        root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
        text=draw_aerial_survey_lines_ecomap,
        **persist_ecomaps_params,
    )
    .call()
)


# %% [markdown]
# ## Create Ecomap Widgets

# %%
# parameters

create_aerial_widgets_params = dict(
    view=...,
)

# %%
# call the task


create_aerial_widgets = (
    create_map_widget_single_view.handle_errors(
        task_instance_id="create_aerial_widgets"
    )
    .partial(
        title="Aerial Survey Lines",
        data=persist_ecomaps,
        **create_aerial_widgets_params,
    )
    .call()
)


# %% [markdown]
# ## Create Dashboard with Patrol Map Widgets

# %%
# parameters

patrol_dashboard_params = dict()

# %%
# call the task


patrol_dashboard = (
    gather_dashboard.handle_errors(task_instance_id="patrol_dashboard")
    .partial(
        details=initialize_workflow_metadata,
        widgets=create_aerial_widgets,
        time_range=define_time_range,
        groupers=configure_grouping_strategy,
        **patrol_dashboard_params,
    )
    .call()
)
