# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import os
from typing import Any

from ecoscope.platform.tasks.config import set_workflow_details as set_workflow_details
from ecoscope.platform.tasks.filter import set_time_range as set_time_range
from ecoscope.platform.tasks.groupby import set_groupers as set_groupers
from ecoscope.platform.tasks.io import persist_text as persist_text
from ecoscope.platform.tasks.results import (
    create_map_widget_single_view as create_map_widget_single_view,
)
from ecoscope.platform.tasks.results import gather_dashboard as gather_dashboard
from ecoscope.platform.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope.platform.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_ext_custom.tasks.io import load_df as load_df
from ecoscope_workflows_ext_custom.tasks.io import (
    persist_df_wrapper as persist_df_wrapper,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    create_geojson_layer as create_geojson_layer_1,
)
from ecoscope_workflows_ext_custom.tasks.results import draw_map as draw_map_1
from ecoscope_workflows_ext_custom.tasks.results import (
    set_base_maps_pydeck as set_base_maps_pydeck,
)
from ecoscope_workflows_ext_custom.tasks.results import (
    view_state_from_geodataframes as view_state_from_geodataframes_1,
)
from ecoscope_workflows_ext_custom.tasks.spatial_ops import (
    reproject_gdf as reproject_gdf,
)
from ecoscope_workflows_ext_ste.tasks.io import get_file_path as get_file_path
from ecoscope_workflows_ext_ste.tasks.spatial_operations import (
    create_survey_transects as create_survey_transects,
)
from ecoscope_workflows_ext_ste.tasks.transformation import (
    subset_columns as subset_columns,
)
from wt_contracts import validate as _validate
from wt_task import task

from .. import metadata as _metadata


def main(params: dict[str, Any], validate_params_schema: bool = True):
    if validate_params_schema:
        _validate(params, _metadata.load_params_schema())

    workflow_details = (
        task(set_workflow_details)
        .validate()
        .set_task_instance_id("workflow_details")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("workflow_details") or {}))
        .call()
    )

    time_range = (
        task(set_time_range)
        .validate()
        .set_task_instance_id("time_range")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(**(params.get("time_range") or {}))
        .call()
    )

    groupers = (
        task(set_groupers)
        .validate()
        .set_task_instance_id("groupers")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(groupers=[], **(params.get("groupers") or {}))
        .call()
    )

    configure_base_maps = (
        task(set_base_maps_pydeck)
        .validate()
        .set_task_instance_id("configure_base_maps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            base_maps=[
                {
                    "url": "https://server.arcgisonline.com/arcgis/rest/services/Elevation/World_Hillshade/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 1,
                    "max_zoom": 20,
                },
                {
                    "url": "https://server.arcgisonline.com/ArcGIS/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}",
                    "opacity": 0.15,
                    "max_zoom": 20,
                },
            ],
            **(params.get("configure_base_maps") or {}),
        )
        .call()
    )

    retrieve_file_params = (
        task(get_file_path)
        .validate()
        .set_task_instance_id("retrieve_file_params")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            output_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("retrieve_file_params") or {}),
        )
        .call()
    )

    load_gdf = (
        task(load_df)
        .validate()
        .set_task_instance_id("load_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            file_path=retrieve_file_params,
            layer=None,
            deserialize_json=True,
            **(params.get("load_gdf") or {}),
        )
        .call()
    )

    survey_lines = (
        task(create_survey_transects)
        .validate()
        .set_task_instance_id("survey_lines")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(gdf=load_gdf, planar_crs=None, **(params.get("survey_lines") or {}))
        .call()
    )

    filter_columns = (
        task(subset_columns)
        .validate()
        .set_task_instance_id("filter_columns")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            df=survey_lines,
            strict=False,
            columns=None,
            exclude=["fid", "FID"],
            **(params.get("filter_columns") or {}),
        )
        .call()
    )

    persist_aerial_gpq = (
        task(persist_df_wrapper)
        .validate()
        .set_task_instance_id("persist_aerial_gpq")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            filetypes=["geoparquet"],
            filename_prefix="survey_lines",
            filename=None,
            sanitize=True,
            df=survey_lines,
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            **(params.get("persist_aerial_gpq") or {}),
        )
        .call()
    )

    transform_gdf = (
        task(reproject_gdf)
        .validate()
        .set_task_instance_id("transform_gdf")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            gdf=survey_lines,
            target_crs="EPSG:4326",
            **(params.get("transform_gdf") or {}),
        )
        .call()
    )

    generate_layers_map = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("generate_layers_map")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "filled": True,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": [85, 107, 47],
                "get_line_color": [85, 107, 47],
                "opacity": 0.25,
                "get_line_width": 1.0,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "",
                "values": [{"label": "Area of Interest", "color": "#556b2f"}],
            },
            geodataframe=load_gdf,
            **(params.get("generate_layers_map") or {}),
        )
        .call()
    )

    aerial_survey_polylines = (
        task(create_geojson_layer_1)
        .validate()
        .set_task_instance_id("aerial_survey_polylines")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            data_url=None,
            layer_style={
                "filled": False,
                "stroked": True,
                "extruded": False,
                "wireframe": False,
                "get_fill_color": [255, 255, 0],
                "get_line_color": [255, 255, 0],
                "opacity": 0.55,
                "get_line_width": 1.0,
                "get_elevation": 0,
                "get_point_radius": 1,
                "line_width_units": "pixels",
                "line_width_scale": 1,
                "line_width_min_pixels": 1,
                "line_width_max_pixels": 5,
            },
            legend={
                "title": "Legend",
                "values": [{"label": "Aerial lines", "color": "#FFFF00"}],
            },
            geodataframe=transform_gdf,
            **(params.get("aerial_survey_polylines") or {}),
        )
        .call()
    )

    zoom_gdf_extent = (
        task(view_state_from_geodataframes_1)
        .validate()
        .set_task_instance_id("zoom_gdf_extent")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            max_zoom=15,
            geodataframes=[load_gdf],
            **(params.get("zoom_gdf_extent") or {}),
        )
        .call()
    )

    draw_aerial_survey_lines_ecomap = (
        task(draw_map_1)
        .validate()
        .set_task_instance_id("draw_aerial_survey_lines_ecomap")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            tile_layers=configure_base_maps,
            static=False,
            title=None,
            max_zoom=15,
            legend_style={"placement": "bottom-right"},
            geo_layers=[aerial_survey_polylines, generate_layers_map],
            view_state=zoom_gdf_extent,
            **(params.get("draw_aerial_survey_lines_ecomap") or {}),
        )
        .call()
    )

    persist_ecomaps = (
        task(persist_text)
        .validate()
        .set_task_instance_id("persist_ecomaps")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            root_path=os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            text=draw_aerial_survey_lines_ecomap,
            filename="aerial_survey.html",
            **(params.get("persist_ecomaps") or {}),
        )
        .call()
    )

    create_aerial_widgets = (
        task(create_map_widget_single_view)
        .validate()
        .set_task_instance_id("create_aerial_widgets")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            title="Aerial Survey Lines",
            data=persist_ecomaps,
            **(params.get("create_aerial_widgets") or {}),
        )
        .call()
    )

    patrol_dashboard = (
        task(gather_dashboard)
        .validate()
        .set_task_instance_id("patrol_dashboard")
        .handle_errors()
        .with_tracing()
        .skipif(
            conditions=[
                any_is_empty_df,
                any_dependency_skipped,
            ],
            unpack_depth=1,
        )
        .partial(
            details=workflow_details,
            widgets=create_aerial_widgets,
            time_range=time_range,
            groupers=groupers,
            **(params.get("patrol_dashboard") or {}),
        )
        .call()
    )

    return patrol_dashboard
