# AUTOGENERATED BY ECOSCOPE-WORKFLOWS; see fingerprint in README.md for details
import json
import os

from ecoscope_workflows_core.graph import DependsOn, Graph, Node
from ecoscope_workflows_core.tasks.config import (
    set_workflow_details as set_workflow_details,
)
from ecoscope_workflows_core.tasks.filter import (
    get_timezone_from_time_range as get_timezone_from_time_range,
)
from ecoscope_workflows_core.tasks.filter import set_time_range as set_time_range
from ecoscope_workflows_core.tasks.io import persist_text as persist_text
from ecoscope_workflows_core.tasks.io import set_er_connection as set_er_connection
from ecoscope_workflows_core.tasks.results import (
    create_plot_widget_single_view as create_plot_widget_single_view,
)
from ecoscope_workflows_core.tasks.results import gather_dashboard as gather_dashboard
from ecoscope_workflows_core.tasks.skip import (
    any_dependency_skipped as any_dependency_skipped,
)
from ecoscope_workflows_core.tasks.skip import any_is_empty_df as any_is_empty_df
from ecoscope_workflows_core.tasks.skip import never as never
from ecoscope_workflows_core.tasks.transformation import (
    convert_values_to_timezone as convert_values_to_timezone,
)
from ecoscope_workflows_ext_ecoscope.tasks.io import get_events as get_events
from ecoscope_workflows_ext_ecoscope.tasks.io import persist_df as persist_df
from ecoscope_workflows_ext_ste.tasks import build_matched_table as build_matched_table
from ecoscope_workflows_ext_ste.tasks import (
    build_unmatched_table as build_unmatched_table,
)
from ecoscope_workflows_ext_ste.tasks import (
    get_unmatched_images as get_unmatched_images,
)
from ecoscope_workflows_ext_ste.tasks import (
    match_images_to_events as match_images_to_events,
)
from ecoscope_workflows_ext_ste.tasks import (
    process_aerial_images as process_aerial_images,
)
from ecoscope_workflows_ext_ste.tasks import (
    upload_images_to_er_events as upload_images_to_er_events,
)

from ..params import Params


def main(params: Params):
    params_dict = json.loads(params.model_dump_json(exclude_unset=True))

    dependencies = {
        "workflow_details": [],
        "time_range": [],
        "er_client_name": [],
        "get_timezone": ["time_range"],
        "images_data": ["get_timezone"],
        "events_data": ["er_client_name", "time_range"],
        "convert_events_to_user_tz": ["events_data", "get_timezone"],
        "matched_data": ["images_data", "convert_events_to_user_tz"],
        "unmatched_data": ["images_data", "matched_data"],
        "persist_matched_csv": ["matched_data"],
        "persist_unmatched_csv": ["unmatched_data"],
        "matched_html": ["matched_data"],
        "persist_matched_html": ["matched_html"],
        "matched_widget": ["persist_matched_html"],
        "unmatched_html": ["unmatched_data"],
        "persist_unmatched_html": ["unmatched_html"],
        "unmatched_widget": ["persist_unmatched_html"],
        "upload_results": ["er_client_name", "matched_data"],
        "persist_upload_results": ["upload_results"],
        "dashboard": [
            "workflow_details",
            "matched_widget",
            "unmatched_widget",
            "time_range",
        ],
    }

    nodes = {
        "workflow_details": Node(
            async_task=set_workflow_details.validate()
            .set_task_instance_id("workflow_details")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("workflow_details") or {}),
            method="call",
        ),
        "time_range": Node(
            async_task=set_time_range.validate()
            .set_task_instance_id("time_range")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("time_range") or {}),
            method="call",
        ),
        "er_client_name": Node(
            async_task=set_er_connection.validate()
            .set_task_instance_id("er_client_name")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial=(params_dict.get("er_client_name") or {}),
            method="call",
        ),
        "get_timezone": Node(
            async_task=get_timezone_from_time_range.validate()
            .set_task_instance_id("get_timezone")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("get_timezone") or {}),
            method="call",
        ),
        "images_data": Node(
            async_task=process_aerial_images.validate()
            .set_task_instance_id("images_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "timezone": DependsOn("get_timezone"),
            }
            | (params_dict.get("images_data") or {}),
            method="call",
        ),
        "events_data": Node(
            async_task=get_events.validate()
            .set_task_instance_id("events_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "time_range": DependsOn("time_range"),
                "event_columns": [
                    "id",
                    "time",
                    "created_at",
                    "serial_number",
                    "event_type",
                    "event_category",
                    "geometry",
                ],
                "include_details": False,
                "include_null_geometry": True,
                "include_display_values": True,
                "raise_on_empty": False,
            }
            | (params_dict.get("events_data") or {}),
            method="call",
        ),
        "convert_events_to_user_tz": Node(
            async_task=convert_values_to_timezone.validate()
            .set_task_instance_id("convert_events_to_user_tz")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("events_data"),
                "timezone": DependsOn("get_timezone"),
                "columns": [
                    "time",
                ],
            }
            | (params_dict.get("convert_events_to_user_tz") or {}),
            method="call",
        ),
        "matched_data": Node(
            async_task=match_images_to_events.validate()
            .set_task_instance_id("matched_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "images_df": DependsOn("images_data"),
                "events_df": DependsOn("convert_events_to_user_tz"),
            }
            | (params_dict.get("matched_data") or {}),
            method="call",
        ),
        "unmatched_data": Node(
            async_task=get_unmatched_images.validate()
            .set_task_instance_id("unmatched_data")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "images_df": DependsOn("images_data"),
                "matched_df": DependsOn("matched_data"),
            }
            | (params_dict.get("unmatched_data") or {}),
            method="call",
        ),
        "persist_matched_csv": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_matched_csv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("matched_data"),
                "filetype": "csv",
                "filename": "matched_images",
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_matched_csv") or {}),
            method="call",
        ),
        "persist_unmatched_csv": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_unmatched_csv")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("unmatched_data"),
                "filetype": "csv",
                "filename": "unmatched_images",
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_unmatched_csv") or {}),
            method="call",
        ),
        "matched_html": Node(
            async_task=build_matched_table.validate()
            .set_task_instance_id("matched_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "matched_df": DependsOn("matched_data"),
            }
            | (params_dict.get("matched_html") or {}),
            method="call",
        ),
        "persist_matched_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_matched_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("matched_html"),
                "filename": "matched_images_preview.html",
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_matched_html") or {}),
            method="call",
        ),
        "matched_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("matched_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Matched Images",
                "data": DependsOn("persist_matched_html"),
            }
            | (params_dict.get("matched_widget") or {}),
            method="call",
        ),
        "unmatched_html": Node(
            async_task=build_unmatched_table.validate()
            .set_task_instance_id("unmatched_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "unmatched_df": DependsOn("unmatched_data"),
            }
            | (params_dict.get("unmatched_html") or {}),
            method="call",
        ),
        "persist_unmatched_html": Node(
            async_task=persist_text.validate()
            .set_task_instance_id("persist_unmatched_html")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "text": DependsOn("unmatched_html"),
                "filename": "unmatched_images_preview.html",
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_unmatched_html") or {}),
            method="call",
        ),
        "unmatched_widget": Node(
            async_task=create_plot_widget_single_view.validate()
            .set_task_instance_id("unmatched_widget")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    never,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "title": "Unmatched Images",
                "data": DependsOn("persist_unmatched_html"),
            }
            | (params_dict.get("unmatched_widget") or {}),
            method="call",
        ),
        "upload_results": Node(
            async_task=upload_images_to_er_events.validate()
            .set_task_instance_id("upload_results")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "client": DependsOn("er_client_name"),
                "matched_df": DependsOn("matched_data"),
            }
            | (params_dict.get("upload_results") or {}),
            method="call",
        ),
        "persist_upload_results": Node(
            async_task=persist_df.validate()
            .set_task_instance_id("persist_upload_results")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "df": DependsOn("upload_results"),
                "filetype": "csv",
                "filename": "aerial_image_upload_results",
                "root_path": os.environ["ECOSCOPE_WORKFLOWS_RESULTS"],
            }
            | (params_dict.get("persist_upload_results") or {}),
            method="call",
        ),
        "dashboard": Node(
            async_task=gather_dashboard.validate()
            .set_task_instance_id("dashboard")
            .handle_errors()
            .with_tracing()
            .skipif(
                conditions=[
                    any_is_empty_df,
                    any_dependency_skipped,
                ],
                unpack_depth=1,
            )
            .set_executor("lithops"),
            partial={
                "details": DependsOn("workflow_details"),
                "widgets": [
                    DependsOn("matched_widget"),
                    DependsOn("unmatched_widget"),
                ],
                "time_range": DependsOn("time_range"),
            }
            | (params_dict.get("dashboard") or {}),
            method="call",
        ),
    }
    graph = Graph(dependencies=dependencies, nodes=nodes)
    results = graph.execute()
    return results
